### ISSUE TITLE
Features list

### ISSUE THREAD

**Issue by raiguard** [raiguard/Factorio-LtnManager#1]
I don't actually use LTN myself, so this issue will be used to create a "features list". People who use LTN and used LTN tracker, feel free to post here with your ideas, thoughts, and requests.

**Comment by narokuu** [comment]
List of Ideas for this mod
1. Alerts for trains being loaded or unloaded wrongly, and timed out deliveries
2. A history of recent deliveries, and the ability to choose how many you see in the GUI
3.The combined inventory of all stations
4. and additional icon on the stations, in the GUI if you use the mod "LTNCombinator" allowing you to change those settings on the map, from anywhere


IN order of most to least importance. tracking deliveries and errors is the main key to LTN, but there are many other functions that are great.
