### ISSUE TITLE
Conflict with Improved Combiantor

### ISSUE THREAD

**Issue by Malidictus** [raiguard/Factorio-LtnManager#100]
#### Describe the Bug

The Improved Combinator mod conflicts with this mod. With the Improved Combinator mod installed and active, LTN's Gui fails to open with a message that "the GUI has become invalid." It does eventually open, but this happens every time it's opened.

Factorio ModPortal link to Improved Combinator:
https://mods.factorio.com/mod/ImprovedCombinator

#### To Reproduce

1. Install the Improved Combinators mod
2. Research and place an Improved Combinator
3. Set the improved combinator to read the contents of a chest, multiply several of them and transmit them as other signals (may be unnecessary)
4. Attempt to open the LTN GUI
5. Receive LTN MANAGER ERROR: the GUI has become invalid.
6. Wait...
7. Attempt to open the LTN GUI
8. Successfully open a fully-functional LTN GUI.
9. Close the LTN GUI
10. Attempt to open the LTN GUI
11. Return to Step 4

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

User name: Malidictus

Save file:
[Solo 3.zip](https://github.com/raiguard/Factorio-LtnManager/files/5050811/Solo.3.zip)

#### Log file

Log File:
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/5050850/factorio-current.log)

**Comment by raiguard** [comment]
This is the fault of the improved combinator mod, and there's nothing I can do about it. I left a reply on your thread on the mod's discussion page explaining the problem. Thanks!

**Comment by Malidictus** [comment]
Thanks for the rapid response. I tried the fix you suggested on the Improved Combinator discussion locally and it seems to have fixed the issue. Much appreciated, let's hope that mod maker implements that change on their end.
