### ISSUE TITLE
Long station names a problem in Inventory view

### ISSUE THREAD

**Issue by mgkr** [raiguard/Factorio-LtnManager#101]
With long station names it's not possible to see the full name of the destination station.

![image](https://user-images.githubusercontent.com/7891248/90367391-1b27c300-e069-11ea-9dfd-a0c9d58d927d.png)

The horizontal scroll bar seems to just scroll a few pixels.

**Comment by OlavStornes** [comment]
Looks like it is already reported [here](https://github.com/raiguard/Factorio-LtnManager/issues/87)

**Comment by raiguard** [comment]
Yeah, it was. Right now I'm rewriting the LTN data iteration part of the mod. After that's done I'll be giving attention to the GUI again and I'll fix this.
