### ISSUE TITLE
freezes up and disconnects

### ISSUE THREAD

**Issue by SGZ-TW-TY-20** [raiguard/Factorio-LtnManager#102]
#### Describe the Bug:
My friend Connected to my server this happens:

When connecting to a server that has LTN Manager enabled, His game freezes up and disconnects, but it seems to only happen with him. As for me hosting the server doesn't have any problem running it.

#### To Reproduce:

Not sure this will work: as it's possible a client issue only.
Have even reinstalled Factorio and all mod used.

1. Host a game on one account.
2. Connect with another account from some other place with around 5 Mbps down and 0.5 Mbps up, that's what I have.
3. Connect and the game should begin to get lower framerates.
4. Get dropped out of the game
 
As I said it might only happen to him. But there might be something overriding the code that we found out could cause a massive desync. ('global.players' referenced [player-data.lua:26)

#### Save file & Username:

[1.0 Bobs MS Dark incomming.zip](https://github.com/raiguard/Factorio-LtnManager/files/5146093/1.0.Bobs.MS.Dark.incomming.zip)

Sgamez & MarcasRealAccount.
Sgamez are the host.

#### Log file:
[factorio-previous.log](https://github.com/raiguard/Factorio-LtnManager/files/5146099/factorio-previous.log):
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/5146100/factorio-current.log)

sending the previous log because we removed this mod and it worked again

**Comment by raiguard** [comment]
Unfortunately, this is happening due to your internet speed. You are only the second person to have this problem who has reported it.

To try and mitigate this will require an update to the Factorio Library mod, not LTNM. I will add a map setting to decrease the number of translations performed per tick, which is set to 50 by default. Have your friend turn this setting down to, say, 10, then try to connect.

I'll let you know once the update is released.

**Comment by raiguard** [comment]
I have released the update, please download it and try decreasing the translation speed.

**Comment by SGZ-TW-TY-20** [comment]
ok.  Thanks, is also that a setting in game ?

**Comment by raiguard** [comment]
Yes, it's a map setting, so go into the map settings and it will be listed under `Factorio Library`.

**Comment by raiguard** [comment]
Did it fix your issue?

**Comment by SGZ-TW-TY-20** [comment]
Yes it did

**Comment by SGZ-TW-TY-20** [comment]
If it helped getting the issue edited to get a better understanding please let me now.

**Comment by raiguard** [comment]
I'm glad that your issue has been solved! Thanks for using the mod.
