### ISSUE TITLE
latest version asks ltn 1.14.5 while latest public ltn version is 1.14.4

### ISSUE THREAD

**Issue by ztnko** [raiguard/Factorio-LtnManager#103]
subj

**Comment by raiguard** [comment]
Oh frick, I thought Optera had released 1.14.5 already. Oops!

The mod depends on changes made in that version, so I guess you'll have to do without until tomorrrow, or downgrade back to 0.2.7. My bad!

**Comment by raiguard** [comment]
Keeping this open for visibility.

**Comment by raiguard** [comment]
The new LTN version is out.
