### ISSUE TITLE
LTN Manager Crash with update 0.3.0

### ISSUE THREAD

**Issue by Hellspawnxxx** [raiguard/Factorio-LtnManager#104]
#### Describe the Bug
![20200918100549_1](https://user-images.githubusercontent.com/60106347/93573398-5e8e8d80-f997-11ea-82f9-9f63ba6e643d.jpg)

- If i load my safe the game stops with an error massage from LTN Manager (see screenshot)
- LTN Manager GUI can´t find the LTN Stations

#### To Reproduce

1. Load the safe file wait a couple of secounds

#### Save file & Username

[Seablock V17_0.18.7z.001.zip](https://github.com/raiguard/Factorio-LtnManager/files/5244272/Seablock.V17_0.18.7z.001.zip)
[Seablock V17_0.18.7z.002.zip](https://github.com/raiguard/Factorio-LtnManager/files/5244273/Seablock.V17_0.18.7z.002.zip)
[Seablock V17_0.18.7z.003.zip](https://github.com/raiguard/Factorio-LtnManager/files/5244274/Seablock.V17_0.18.7z.003.zip)
[Seablock V17_0.18.7z.004.zip](https://github.com/raiguard/Factorio-LtnManager/files/5244278/Seablock.V17_0.18.7z.004.zip)
[Seablock V17_0.18.7z.005.zip](https://github.com/raiguard/Factorio-LtnManager/files/5244289/Seablock.V17_0.18.7z.005.zip)

This is my safe file, split into 5 parts (7z) because of size. Remove the ".zip" at the end. I added them because github doesnt accept the files with out it.

Please also provide your in-game username so I can reproduce the conditions exactly.
"Hellspawn"

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/5244316/factorio-current.log)

**Comment by alibaba258** [comment]
Same Problem here

**Comment by dcbishop** [comment]
I'm also getting a crash on load, although a slightly different error message.
```
The mod LTN Manager [ALPHA] (0.3.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/util.lua:80: attempt to concatenate field 'fetching-from' (a nil value)
stack traceback:
	__LtnManager__/scripts/util.lua:80: in function 'get_status_string'
	__LtnManager__/scripts/ltn-data.lua:241: in function 'callback'
	__flib__/table.lua:196: in function <__flib__/table.lua:169>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:494: in function 'iterate'
	__LtnManager__/control.lua:157: in function <__LtnManager__/control.lua:153>
```

**Comment by raiguard** [comment]
Thanks for the reports, this is fixed for the next release. This is what I get for not testing multiplayer.

A few notes:
1) You don't need `RaiLuaLib` anymore, it's been deprecated for months, I use `flib` now
2) Holy crap your base is huge
3) I need to fix this:

![image](https://user-images.githubusercontent.com/3515394/93628535-f2feed00-f9a3-11ea-8289-2f6a146f263a.png)

Thanks again!

**Comment by Hellspawnxxx** [comment]
Thanks for fixing it so fast! :)
1. Ok, i didnt know.
2. Yeah, i played that map for "some" time no
3. no clue what you talking about but i guess it will be awsome :)

No problem and you are welcome to use the map for testing! No i can be sure my map is loading when you update the mod! :D

Much love for you work on that mod! <3
