### ISSUE TITLE
crash after LTN tries to find a location that supplies a resource but cant find any 

### ISSUE THREAD

**Issue by gintsligotnis** [raiguard/Factorio-LtnManager#106]
Error Log : 
The mod LTN Manager [ALPHA] (0.3.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:289: attempt to compare two nil values
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:289: in function <__LtnManager__/scripts/ltn-data.lua:288>
	[C]: in function 'sort'
	__LtnManager__/scripts/ltn-data.lua:288: in function 'callback'
	__flib__/table.lua:196: in function <__flib__/table.lua:169>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:506: in function 'iterate'
	__LtnManager__/control.lua:157: in function <__LtnManager__/control.lua:153>

**Comment by raiguard** [comment]
Please follow the bug report template and provide all of that information. It exists for a reason.

**Comment by Hellspawnxxx** [comment]
Hi, i dont know if i have the same or a different Bug. It look´s a kind of the same error message:

![20200920140032_1](https://user-images.githubusercontent.com/60106347/93710882-22e7f500-fb4a-11ea-8b69-fcdfb3bc3efb.jpg)

I´m not sure at the moment what caused the problem to happen but i will try to reporduce it and will give you some feadback as soon as i figured it out.

**Comment by Hellspawnxxx** [comment]
Mh, sorry i failed to reporduce it. :( 
When i had the error i just placed some new ghost trains on the rail track to add them to the LTN Network. I did the same again but no error happend the 2nd time.

**Comment by H4nSolo** [comment]
**Step to reproduced:**
Simply dismantle a train in one of the train depots if it has already been assigned an active order.

**Comment by raiguard** [comment]
@Hellspawnxxx That error is was also reported by someone else, and while I was also unable to reproduce it, I am reasonably confident that I have fixed it.

@gintsligotnis Please provide me with the save file that your error occured on, as well as you `factorio-current.log` and in-game username.

**Comment by raiguard** [comment]
Closing due to lack of response from @gintsligotnis.
