### ISSUE TITLE
Mod crash at train deconstruction

### ISSUE THREAD

**Issue by IshFx** [raiguard/Factorio-LtnManager#107]
#### Describe the Bug

Mod crashes when i deconstruct a train part (locomotive or wagon). It doesn't happen all the time, but if i keep deconstructing, it crashes at some time.

Video: [https://imgur.com/a/yE6Vuw0](https://imgur.com/a/yE6Vuw0)
Error:
![image](https://user-images.githubusercontent.com/23222270/93670466-dd6cee80-fa9b-11ea-8aea-8ead0fd2c8d6.png)

#### To Reproduce

1. Deconstruct a train or wagon
2. Repeat
3. Boom! Crash.

#### Save file & Username

I used the LTN demo save to reproduce the bug. Used mods are LTN, LTNM, and creative mod.
[https://filebin.net/8e7vcv34e8ynqacy](https://filebin.net/8e7vcv34e8ynqacy)
Save username : Optera

#### Log file

[https://filebin.net/8e7vcv34e8ynqacy](https://filebin.net/8e7vcv34e8ynqacy)

**Comment by cacomixl8** [comment]
This happened to me as well, however, I do not have the crash log.

I had a LCCL and tried to delete the cargo wagons to make it LFFL.

Factorio hard crash, I'll get the error if it happens again. Been saving my game extra hard.

**Comment by raiguard** [comment]
Thanks for the report, this has been fixed for the next release.
