### ISSUE TITLE
Per-Surface GUIs/Filters

### ISSUE THREAD

**Issue by cameronleger** [raiguard/Factorio-LtnManager#108]
#### Is your feature request related to a problem? Please describe.

Thankfully, LTN handles multiple surfaces just fine, so with mods like Space Exploration it's not necessary to separate surfaces by Network IDs manually.

#### Describe the solution you'd like

The GUI could have filters or perhaps a global dropdown for selecting the surface. Ideally, each specific surface would display only the trains, stations, requests, etc. that mattered for that surface.

#### Additional context

Since multiple surfaces are used in specific situations and not all the time, the default could be all-surface or the current surface. It'd be nice to select the surface if desired, but it could instead only show the current surface without the option to view others.

**Comment by raiguard** [comment]
This will be implemented in the next major version, which will include a full GUI rewrite:

![image](https://user-images.githubusercontent.com/3515394/94348948-af3c6100-fffd-11ea-9632-2eff63bdaf35.png)

**Comment by raiguard** [comment]
This has been implemented for v0.4.0.

![image](https://user-images.githubusercontent.com/3515394/95821502-489a9100-0ce7-11eb-8d05-86964ded4b3e.png)
