### ISSUE TITLE
Error with mods replacing rolling stock

### ISSUE THREAD

**Issue by Yousei9** [raiguard/Factorio-LtnManager#11]
Reproduction with MultipleUnitTrainControl:
- open ltn demo
- make sure MU Control is set to tech unlock
- research MU tech 

Error: 
```
Error MainLoop.cpp:1202: Exception at tick 4795248: The mod LTN - Logistic Train Network (1.12.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::on_nth_tick(2)
The mod LTN Manager [ALPHA] (0.1.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::Custom event (ID 234)
__LtnManager__/scripts/data-manager.lua:624: attempt to index local 'train' (a nil value)
stack traceback:
	__LtnManager__/scripts/data-manager.lua:624: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
stack traceback:
	__LogisticTrainNetwork__/script/dispatcher.lua:64: in function <__LogisticTrainNetwork__/script/dispatcher.lua:20>
stack traceback:
	[C]: in function 'raise_event'
	__LogisticTrainNetwork__/script/dispatcher.lua:64: in function <__LogisticTrainNetwork__/script/dispatcher.lua:20>
```

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/4460589/factorio-current.log)

**Comment by raiguard** [comment]
Hmm, this is happening because when the train gets invalidated, the train's ID changes. So the `train_id` that comes as part of the event doesn't actually point to any valid train. LTN Tracker also crashes due to this.

Is this a bug on your end?

**Comment by Yousei9** [comment]
On my end I raise delivery failed.
If that doesn't contain the old id, yes I'm doing something wrong.

**Comment by Yousei9** [comment]
Ah my bad... I was thinking of older versions.
Current LTN does migrate deliveries. You have to also handle on_train_created and update train and train.id.
