### ISSUE TITLE
Crash on Nil Status

### ISSUE THREAD

**Issue by OldPapabear** [raiguard/Factorio-LtnManager#112]
#### Describe the Bug

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:221: attempt to index field 'status' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:221: in function 'callback'
	__flib__/table.lua:196: in function <__flib__/table.lua:169>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:544: in function 'iterate'
	__LtnManager__/control.lua:157: in function <__LtnManager__/control.lua:153>

#### To Reproduce

1. Stop Trains from exiting Depot
2. Wait.  Once all trains have returned it may take a few minutes to occur.
3. Was Pasting new Depot setup in case that helps.

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

Upload the save file where the bug occured. If the file is too large for GitHub, use an alternative file service.

Please also provide your in-game username so I can reproduce the conditions exactly.

_IF YOU DO NOT UPLOAD A SAV
[Expensive World.zip](https://github.com/raiguard/Factorio-LtnManager/files/5263525/Expensive.World.zip)
User: OldPapabear
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/5263528/factorio-current.log)

#### Log file

Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

**Comment by jaapveeden** [comment]
same here, just after last update!

The mod LTN Manager [ALPHA] (0.3.4) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:455: attempt to concatenate field 'to' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:455: in function '?'
	__LtnManager__/scripts/ltn-data.lua:544: in function 'iterate'
	__LtnManager__/control.lua:157: in function <__LtnManager__/control.lua:153>

**Comment by raiguard** [comment]
I apologize for the huge amount of bugs recently! But that's why there's a giant `[ALPHA]` sticker on the title. :D

Anyway, fixed for the next release. This bug was gnarly and took me almost two hours to solve!
