### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gauchotche** [raiguard/Factorio-LtnManager#113]
![image](https://user-images.githubusercontent.com/33750853/93999939-d4667080-fd6c-11ea-94e1-56b604d9a80b.png)

**Comment by H4nSolo** [comment]
Please fill out the complete bug report to analyze your crash


> #### Describe the Bug
> 
> A clear and concise description of what the bug is.
> 
> #### To Reproduce
> 
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> Be certain to reproduce the issue on the same save file that you upload.
> 
> #### Save file & Username
> 
> Upload the save file where the bug occured. If the file is too large for GitHub, use an alternative file service.
> 
> Please also provide your in-game username so I can reproduce the conditions exactly.
> 
> _IF YOU DO NOT UPLOAD A SAVE FILE AND PROVIDE YOUR USERNAME, THE BUG REPORT WILL BE IGNORED UNTIL YOU DO._
> 
> #### Log file
> 
> Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).
>

**Comment by dennisahlin** [comment]
I got this error too!
Out of the blue, without doing anything special. A few minutes in when I've tried adding a phospor outpost.

Logs:
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/5277758/factorio-current.log)

Name:
BadDay

Save:
https://www.dropbox.com/t/BCTNs7DhrXahiykR

**Comment by raiguard** [comment]
@dennisahlin Unfortunately I was unable to reproduce the error after waiting for ten minutes on the save you provided. If you can somehow find a way to consistently reproduce it, please let me know!

**Comment by dennisahlin** [comment]
Well... Me neither. It happened twice, then I tried again with higher frequency saves and doing roughly the same thing, but it doesn't happen now.

But this shouldn't be hard to fix by the error message, right? There's a null check missing in ltn-data.lua in line 455. Probably this happens when a train gets an alert, but doesn't have a destination.
![image](https://user-images.githubusercontent.com/1439413/94238617-2986bb80-ff00-11ea-9618-87f3ab7ebab8.png)

**Comment by raiguard** [comment]
Yes, but that's putting a band-aid over the real issue. The actual bug that needs solving is _why_ is that value `nil`? That's why I need a reproducible test case - so I can figure out the circumstances leading up to this.

**Comment by dennisahlin** [comment]
True, but I guess there could be multiple reasons, like if you removed the station? (I didn't in this case, though) :)

**Comment by raiguard** [comment]
The value is the station's name, so even if the station gets removed, that won't affect it.

**Comment by dennisahlin** [comment]
Ah, well I don't know. Personally i would rather add a null check that I don't know the reason for than having the users' game crash :) But I'll post save file again if it occurs.

**Comment by PGScully** [comment]
I just started hitting this tonight.

[Save file](https://drive.google.com/file/d/1JjUixLaQzL3QAlW1_u-FTXaWjXIXUcD9/view?usp=sharing) - Should crash within a few seconds of loading
[Log file](https://drive.google.com/file/d/1Gd3CJHXXNdb9EJRrWZll4tgU8l2-BWD2/view?usp=sharing)
Username: Gatsukama

**Comment by raiguard** [comment]
@PGScully Hurrah! Your save was the chosen one! I have finally reproduced it.

I'll get to the bottom of this and get a patch out ASAP.
