### ISSUE TITLE
crash Error MainLoop.cpp:1207: Exception at tick 129529825

### ISSUE THREAD

**Issue by JanEggers** [raiguard/Factorio-LtnManager#116]
#### Describe the Bug

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:455: attempt to concatenate field 'to' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:455: in function '?'
	__LtnManager__/scripts/ltn-data.lua:544: in function 'iterate'
	__LtnManager__/control.lua:157: in function <__LtnManager__/control.lua:153>

#### To Reproduce

load the save and wait some time ca 30 sec

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/5284915/factorio-current.log)
[py al.zip](https://github.com/raiguard/Factorio-LtnManager/files/5284917/py.al.zip)

**Comment by JanEggers** [comment]
seems similar to #112 but im using 0.3.5

**Comment by raiguard** [comment]
Duplicate of #113
