### ISSUE TITLE
Crash when I put a train in manual

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-LtnManager#118]
#### Describe the Bug
I wanted to change the configuration of a train parked in a depot, so I put it in manual, so that it would not leave while I am changing its wagons.
When I did that, the game crashs!

#### To Reproduce

1. Go to the depot with on trains stopped
2. Change the train to manual

* I'm not able to reproduce this again!

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

Username: Dominiquini
Save File:  _My save is very modded! I don't think will be useful!_

#### Log file

---
7476.501 Error MainLoop.cpp:1207: Exception at tick 36013349: The mod LTN Manager [ALPHA] (0.3.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:163: attempt to index local 'schedule' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:163: in function 'callback'
	__flib__/table.lua:201: in function <__flib__/table.lua:173>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:580: in function 'iterate'
	__LtnManager__/control.lua:155: in function <__LtnManager__/control.lua:151>

---

**Comment by raiguard** [comment]
Please provide the save file, no matter how modded it is. I have 1,010 mods in my mods folder from bug reports. :)

**Comment by Dominiquini** [comment]
Save File: https://ufile.io/bbh58hnp (I couldn't upload it here, because the file is too big!)

But as I explained, I was only able to reproduce the bug once. After the first crash, I tried to do the same action and everything worked correctly.

I hope this helps!

Thanks.

**Comment by raiguard** [comment]
Thank you, I've fixed it for the next release.

**Comment by Dominiquini** [comment]
Thanks for the fix.

Great mod!
