### ISSUE TITLE
Crash after update when loading previously working save file

### ISSUE THREAD

**Issue by RalfJung** [raiguard/Factorio-LtnManager#119]
#### Describe the Bug

After loading our save file that worked fine with v0.3.6, a crash occurs with v0.3.7:

```
 678.992 Error MainLoop.cpp:1207: Exception at tick 41152794: The mod LTN Manager [ALPHA] (0.3.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:286: attempt to index field '?' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:286: in function <__LtnManager__/scripts/ltn-data.lua:285>
	[C]: in function 'sort'
	__LtnManager__/scripts/ltn-data.lua:285: in function 'callback'
	__flib__/table.lua:201: in function <__flib__/table.lua:173>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:584: in function 'iterate'
	__LtnManager__/control.lua:155: in function <__LtnManager__/control.lua:151>
 678.993 Error ClientMultiplayerManager.cpp:98: MultiplayerManager failed: "The mod LTN Manager [ALPHA] (0.3.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:286: attempt to index field '?' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:286: in function <__LtnManager__/scripts/ltn-data.lua:285>
	[C]: in function 'sort'
	__LtnManager__/scripts/ltn-data.lua:285: in function 'callback'
	__flib__/table.lua:201: in function <__flib__/table.lua:173>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:584: in function 'iterate'
	__LtnManager__/control.lua:155: in function <__LtnManager__/control.lua:151>"
```

I can provide a safe file if required, but our game is rather large. Since this happens without doing anything, I expect we will not be the only ones affected.

**Comment by raiguard** [comment]
Yes, _please_ provide your save file.

**Comment by RalfJung** [comment]
Any advice for where I can upload a 100 MiB savefile?

**Comment by RalfJung** [comment]
Hopefully this works: https://rapidshare.io/33c/Hex71.zip
My username is "DerRalfinator".

**Comment by raiguard** [comment]
Unfortunately I am unable to reproduce the crash. I loaded up your save and left it running for 20 minutes without a crash. I also loaded it in multiplayer and nothing happened.

Please clarify: this happens every time you try to start the game? Also, am I correct that this is a multiplayer map?

**Comment by RalfJung** [comment]
Yes, this is a multiplayer map. We loaded that savegame... well actually we loaded the savegame of one of my friends, not mine, but they were created at basically the same time. I will try to acquire the concrete save that we loaded.

**Comment by RalfJung** [comment]
We were unable to reproduce this problem, and on a later savefile the new version of the mod loads just fine... so sorry for the noise, seems I cannot actually produce a savefile.

Also let me use this opportunity to thank you for this mod, is is extremely useful when handling a large base that heavily relies on LTN for resource transport and management. :)

**Comment by raiguard** [comment]
Alright, if it ever happens again, please let me know! Thanks for using the mod. :)
