### ISSUE TITLE
LTN Manager ALPHA

### ISSUE THREAD

**Issue by frightlord** [raiguard/Factorio-LtnManager#120]
#### To Reproduce

![LTn Error-crash](https://user-images.githubusercontent.com/72296671/94986702-0ba10280-0561-11eb-923e-1d81c047e270.PNG)
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/5321302/factorio-current.log)

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

Upload the save file where the bug occured. If the file is too large for GitHub, use an alternative file service.

Please also provide your in-game username so I can reproduce the conditions exactly.

_IF YOU DO NOT UPLOAD A SAVE FILE AND PROVIDE YOUR USERNAME, THE BUG REPORT WILL BE IGNORED UNTIL YOU DO._

#### Log file

Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

**Comment by raiguard** [comment]
Please provide the save file and tell me how to cause the crash.

**Comment by raiguard** [comment]
Please provide a save file and I'll re-open the issue.
