### ISSUE TITLE
Wrong focus

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-LtnManager#121]
#### Describe the Bug

In the GUI, on tab "Inventory", in the section "Trains"; if I click on a requester station, the map get focus on the provider station!

#### To Reproduce

1. Open the GUI
2. Click on tab Inventory
3. Select some resource in transit
4. On the right, click on the requester station
5. The map get focus on the provider station

#### Save file & Username

* I don't think this is relevant!

#### Log file

* I don't think this is relevant!

Thanks.

**Comment by raiguard** [comment]
Thanks, this has been fixed for the next release.
