### ISSUE TITLE
Enable/Disable Dispatcher

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-LtnManager#122]
#### Is your feature request related to a problem? Please describe.

The last version of LTN (1.14.6) introduced a way to enable/disable dispatcher of trains, but nothing is indicated on the LTN Manager GUI

#### Describe the solution you'd like

Create a button to allow us enable or disable the dispatcher. Or at least some indicator if it is enabled or disabled.

#### Additional context

---

Thanks

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/95670490-10f5e280-0b49-11eb-89e6-809c2ef2a09e.png)

Added for v0.4.0.
