### ISSUE TITLE
Gui Idea

### ISSUE THREAD

**Issue by SGZ-TW-TY-20** [raiguard/Factorio-LtnManager#125]
https://cdn.discordapp.com/attachments/697564089907675219/764985524548665354/unknown.png
Minimize half of the gui to be able to use it on both sides when kept open?

**Comment by raiguard** [comment]
I'm not sure I understand what you're asking. Regardless, that screen is being redesigned, so it might not be possible to implement what you want.

**Comment by raiguard** [comment]
The new inventory screen has only the left part, as the right part is made redundant by search improvements on the stations and depots tabs.

**Comment by SGZ-TW-TY-20** [comment]
Ok, I'll see how the 0.4 will be. sorry for not responding i forgot about the post. as am not checking mail as often as the factorio page
