### ISSUE TITLE
Train slots crash

### ISSUE THREAD

**Issue by VolatileDawn** [raiguard/Factorio-LtnManager#126]
#### Describe the Bug

While using a mod to decrease the number of train slots, LTN manager alpha crashed:
The mod LTN Manager [ALPHA] (0.3.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:286: attempt to index field '?' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:286: in function <__LtnManager__/scripts/ltn-data.lua:285>
	[C]: in function 'sort'
	__LtnManager__/scripts/ltn-data.lua:285: in function 'callback'
	__flib__/table.lua:201: in function <__flib__/table.lua:173>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:584: in function 'iterate'
	__LtnManager__/control.lua:155: in function <__LtnManager__/control.lua:151>

#### To Reproduce

1. Use mod "Config train specifications" by DellAquila to increase your cargo wagon size, in this case to "720" percent, in startup settings. Save game. Then decrease the value, in this case to "100" percent. Then load the game, crashes immediately. 

Ok you can have my save file but I have a lot of mods... have fun with needless Train base!

#### Save file & Username

VolatileDawn
[TrainTown02-11.zip](https://github.com/raiguard/Factorio-LtnManager/files/5371243/TrainTown02-11.zip)

_IF YOU DO NOT UPLOAD A SAVE FILE AND PROVIDE YOUR USERNAME, THE BUG REPORT WILL BE IGNORED UNTIL YOU DO._

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/5371288/factorio-current.log)

Also thank you your mod is great and wonderful!

**Comment by raiguard** [comment]
Thanks for the report, this is fixed for the next release.
