### ISSUE TITLE
Setting for length of history

### ISSUE THREAD

**Issue by power-5000** [raiguard/Factorio-LtnManager#127]
#### Is your feature request related to a problem? Please describe.

Not really an issue however sometimes I want to establish a trend of where is all of X resource going when I'm running low. I can search the history to see where that resource is being delivered however that history often only goes back 3-4 supply runs for the resource. I have a very busy LTN network so there are lots of deliveries and I can't easily establish long lasting trends.

#### Describe the solution you'd like

It would be really nice if there was a mod setting along the lines of "number of deliveries saved in history" this setting could be set to whatever the user wants 100, 500, 5000 etc.

#### Additional context

https://gyazo.com/7c4c5168b7cefb6dc6d78d0ce3a55c67

**Comment by raiguard** [comment]
Sure, I'll add this in v0.4.0. However, increasing the length of the history will degrade performance on all fronts, so keep that in mind.
