### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-LtnManager#128]
#### Describe the Bug

The game crash!

#### To Reproduce

I'm ridinf a personal train (I simply put some train from my inventory on the rails) and the game crash when I got off the train after it arrived at a station!

#### Save file & Username

Username: Dominiquini

* This happens only one time. I'm unable to reproduce this bug afterwards!

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/5399286/factorio-current.log)

---
12014.220 Error MainLoop.cpp:1207: Exception at tick 50721228: The mod LTN Manager [ALPHA] (0.3.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::Custom event (ID 308)
__LtnManager__/scripts/ltn-data.lua:630: attempt to index field 'working_data' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:630: in function <__LtnManager__/scripts/ltn-data.lua:628>
stack traceback:
	__LogisticTrainNetwork__/script/dispatcher.lua:137: in function <__LogisticTrainNetwork__/script/dispatcher.lua:20>
stack traceback:
	[C]: in function 'raise_event'
	__LogisticTrainNetwork__/script/dispatcher.lua:137: in function <__LogisticTrainNetwork__/script/dispatcher.lua:20>
---

**Comment by Dominiquini** [comment]
I have another crash now. I believe that is the same bug:

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/5412622/factorio-current.log)

Thanks.

**Comment by raiguard** [comment]
Thanks, fixed for the next release.
