### ISSUE TITLE
Long station names

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-LtnManager#129]
#### Is your feature request related to a problem? Please describe.

In the "History"tab, long station names make the window weird!

#### Describe the solution you'd like

Broke the station name (with ... in the end) instead of putting a horizontal scroll in the window.

#### Additional context

![factorio_7OGWL2qY4o](https://user-images.githubusercontent.com/1180808/96408689-64f06f00-11ba-11eb-97f1-a4e0b4f2c2ab.jpg)

Thanks

**Comment by power-5000** [comment]
Personally I prefer the Scroll bar I hate when I have to hover over things to see their full name. maybe a mod setting? Also you could use[ rich text](https://wiki.factorio.com/Rich_text) to name your stations. that way it is easy to see what they are at a glance and also shortens the names.

**Comment by raiguard** [comment]
The GUI rewrite actually addresses this. The names will be truncated if they're too long, and you'll have to hover over them to see the full name.

**Comment by Dominiquini** [comment]
Thanks for the suggestion. I will starting using icons to name my train stations!
