### ISSUE TITLE
LTN Combinator integration

### ISSUE THREAD

**Issue by therock182** [raiguard/Factorio-LtnManager#13]
hi,

thanks for the new ltn manager.
can you please support ltn combinator like the old ltn tracker. it was possible to change the input signals for every trainstation out of the tracker itself.

thx

**Comment by raiguard** [comment]
This is in the plans for the near future.

**Comment by maxtimbo** [comment]
+1 for this please. This was the only feature I really used with LTN tracker

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/80559333-69ba3000-899a-11ea-82cd-dfab581c53cd.png)
It is in!
