### ISSUE TITLE
Not compatible with multi surfaces & multi forces

### ISSUE THREAD

**Issue by RitnDev** [raiguard/Factorio-LtnManager#130]
Hello, I currently have a server running with RitnTeleportation which allows you to create a surface per player with its own strength also in a multiplayer game.

This server has LTN and also your mod.

In the main GUI, in the "stations" and "Inventory" tab all the information displayed mixes all the surfaces combined instead of the one on which we are playing.
It's more of an annoyance than a bug.

On the other hand I have a command which allows to remove a surface and a force of a player if he decides not to play anymore.
This command crashed the server. Here is the log related to this crash:

`Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/control.lua:161 : attempt to index local 'player_table' (a nil value)
stack traceback:
__LtnManager__/control.lua:161: in function <__LtnManager__/control.lua:151>`

thank you.

**Comment by raiguard** [comment]
FIltering by surface is coming in v0.4.0 with the GUI rewrite.

As for the crash, I have fixed that specific one for the next release, but there are other places where it could crash as well. I will also fix those for v0.4.0 since it will be a bit of a large effort.
