### ISSUE TITLE
warning messages in up-left corner of the screen dissapear some time ago

### ISSUE THREAD

**Issue by ztnko** [raiguard/Factorio-LtnManager#131]
i don't remember when i lost these alert messages https://puu.sh/GJAR5/51f62bc537.png  these messages appeared when something appeared in Alerts tab of ltn manager. Now i don't receive them so i don't see Alerts when it happens and can't react. Every single alert must be solved asap before problem multiplies but i need manually open ltn manager alert tab to see if it's empty. it's me changed something or why these so usefull warning indication dissapeared? i dozen times check every single setting of ltn and ltn manager but can't return these warnings.

**Comment by ztnko** [comment]
i find these `Version: 0.3.0
Date: 2020-09-17
   Changes:
    - Removed alert popups in favor of LTN's new built-in notifications`
you can't configure these built-in notification to show alerts. these notifications means exactly nothing and not connected with alerts that i need to show asap. for example https://puu.sh/GJBHW/b47028f414.jpg
there i need to solve alerts problem while notifications show me some useless info about lack of trains. please return these old school poppups that exists since ltn tracker. these popups is usefull key feature that prevent me to manually open alert tab every 5mins while ltn built-in notifications is just useless flashing thing that shows nothing and turned off 99% time.

**Comment by ztnko** [comment]
i experiment a bit and what i find:
manager alerts shows:
1.  delivery timeout - super usefull. 99% it's traffic jam
2.  wrong delivery - super usefull - need to be solved asap.

ltn '1: errors&warnings' console setting shows:
1. delivery timeout
2. lack of trains - i don't care. it's strategic info - i don't need to  react to it asap
3. lack of stations that provides goods - i don't care. it's strategic info - i don't need to  react to it asap

ltn inbuild flashing indication shows:
1. lack of trains 
2.  wrong delivery

so oldschool alert popups shows me exactly what i need to react
ltn console messages don't show me 'wrong delivery'
ltn inbuild flashing indication don't show me delivery timeouts

thats why i want to have these old popup messages...

**Comment by raiguard** [comment]
I removed the LTNM alerts because the LTN alerts do, in fact, show everything that they did. I will think about solutions for this for a future version, but not until after the main GUI rewrite.

**Comment by raiguard** [comment]
I'm not going to be re-adding custom notifications. Sorry.

I do have tentative plans to write an advanced notifications mod, and if I do that, I will integrate LTNM.
