### ISSUE TITLE
Opening LTN Manager crashes server.

### ISSUE THREAD

**Issue by sassault** [raiguard/Factorio-LtnManager#133]
Some Trains are in deadlock. I need to send them away manually because the LTN timed out.

This triggers a "delivery not completed" alert.

Opening the LTN Manager afterwards kills server. This was reproduced twice.

 531.835 Error MainLoop.cpp:1207: Exception at tick 524692570: The mod LTN Manager [ALPHA] (0.2.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_lua_shortcut (ID 34)
__LtnManager__/scripts/gui/main-tabs/alerts.lua:104: attempt to index local 'alert_data' (a nil value)
stack traceback:
	__LtnManager__/scripts/gui/main-tabs/alerts.lua:104: in function 'update'
	__LtnManager__/scripts/gui/main.lua:332: in function 'update'
	__LtnManager__/scripts/gui/main.lua:359: in function 'update_active_tab'
	__LtnManager__/scripts/gui/main.lua:373: in function 'open'
	__LtnManager__/scripts/gui/main.lua:407: in function 'toggle'
	__LtnManager__/control.lua:148: in function <__LtnManager__/control.lua:143>
 531.836 Error ServerMultiplayerManager.cpp:90: MultiplayerManager failed: "The mod LTN Manager [ALPHA] (0.2.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_lua_shortcut (ID 34)
__LtnManager__/scripts/gui/main-tabs/alerts.lua:104: attempt to index local 'alert_data' (a nil value)
stack traceback:
	__LtnManager__/scripts/gui/main-tabs/alerts.lua:104: in function 'update'
	__LtnManager__/scripts/gui/main.lua:332: in function 'update'
	__LtnManager__/scripts/gui/main.lua:359: in function 'update_active_tab'
	__LtnManager__/scripts/gui/main.lua:373: in function 'open'
	__LtnManager__/scripts/gui/main.lua:407: in function 'toggle'
	__LtnManager__/control.lua:148: in function <__LtnManager__/control.lua:143>"
 531.836 Info ServerMultiplayerManager.cpp:769: updateTick(524692570) changing state from(InGame) to(Failed)

**Comment by sassault** [comment]
Savegame and Repro-Steps can be provided, but due to the complexity of the savefile are hard to bewritten :/

**Comment by raiguard** [comment]
Your version of the mod is significantly out of date. Please update to the latest version.
