### ISSUE TITLE
Adjustable window size

### ISSUE THREAD

**Issue by bemerged** [raiguard/Factorio-LtnManager#135]
#### Is your feature request related to a problem? Please describe.

I usually use very long names for stations, to somehow categorize them. In the station overview of your window, you cut long names and substitute the remaining part with "...".

#### Describe the solution you'd like

I would really like to be able to change the window size, as I'm playing on a 2k Screen, I got a bunch of space for it. It would also be a solution, if the name shows up when hovering over it.

**Comment by raiguard** [comment]
I do not have plans to make the window size adjustable. However, the GUI redesign will be significantly larger, so this problem will be mitigated somewhat anyway.
