### ISSUE TITLE
 control + f

### ISSUE THREAD

**Issue by trikiman** [raiguard/Factorio-LtnManager#139]
if i rebind "focus search"(control+f) for other button (i use mouse4) 
 on ltnManager it is not work.  
 can u plz fix that, and can u give manual (if possible(maybe need somewhere just change one line)) how to rebind to mouse4  current version mod?
  factorio ver : 1 0 0
  LtnManager ver:  0 3 9
  Thanks.

**Comment by trikiman** [comment]
(

**Comment by raiguard** [comment]
Fixed for the next release.
