### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by vipje** [raiguard/Factorio-LtnManager#14]
243.044 Error MainLoop.cpp:1202: Exception at tick 28849954: The mod LTN Manager [ALPHA] (0.1.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_gui_click (ID 1)
__LtnManager__/gui/stations.lua:143: bad argument #2 of 4 to 'max' (number expected, got nil)
stack traceback:
        [C]: in function 'max'
        __LtnManager__/gui/stations.lua:143: in function 'update'
        __LtnManager__/gui/main.lua:261: in function 'update'
        __LtnManager__/gui/main.lua:280: in function 'update_active_tab'
        __LtnManager__/gui/main.lua:57: in function 'handler'
        __RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
 243.052 Error ServerMultiplayerManager.cpp:90: MultiplayerManager failed: "The mod LTN Manager [ALPHA] (0.1.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_gui_click (ID 1)
__LtnManager__/gui/stations.lua:143: bad argument #2 of 4 to 'max' (number expected, got nil)
stack traceback:
        [C]: in function 'max'
        __LtnManager__/gui/stations.lua:143: in function 'update'
        __LtnManager__/gui/main.lua:261: in function 'update'
        __LtnManager__/gui/main.lua:280: in function 'update_active_tab'
        __LtnManager__/gui/main.lua:57: in function 'handler'
        __RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>"

**Comment by raiguard** [comment]
Thanks. I actually already fixed this when I was doing something else, the fix will be included in the next version.
