### ISSUE TITLE
Crash when using inventory tab.

### ISSUE THREAD

**Issue by RuboGubo** [raiguard/Factorio-LtnManager#141]
The bug occurs whenever the inventory tab is used, irrelevant if it is hosted by me or a friend or if it is in single player. The search bar does not seem to influence the result, and the crash happens immediately without haging.

#### To Reproduce

1. Go to 'LNT manager window'
2. Click on 'inventory'
3. See the error

Be certain to reproduce the issue on the same save file that you upload. - Done

#### Save file & Username

Username: 
RuboGubo

File:
[ok 3.zip](https://github.com/raiguard/Factorio-LtnManager/files/6607874/ok.3.zip)

Log File:
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/6607908/factorio-current.log)

**Comment by RuboGubo** [comment]
Note: Moving for some reason stops the error.

**Comment by raiguard** [comment]
The GUI was completely rewritten, so I'm going to close this for now. Let me know if it happens again after updating to 0.4.0.
