### ISSUE TITLE
Crash when opening the LNT window

### ISSUE THREAD

**Issue by RuboGubo** [raiguard/Factorio-LtnManager#142]
#### Describe the Bug

Whenever the LNT window is opened, the game crashes. Similar to issue #141 

#### To Reproduce

1. Go to 'LNT window'
2. See the error

#### Details

Username: RuboGubo

Save Game: 
[Bug report.zip](https://github.com/raiguard/Factorio-LtnManager/files/6609817/Bug.report.zip)

Log: 
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/6609829/factorio-current.log)

**Comment by raiguard** [comment]
Duplicate of #141
