### ISSUE TITLE
LTN Wrong error message missing cargo

### ISSUE THREAD

**Issue by sebbi08** [raiguard/Factorio-LtnManager#143]
Error message or bug description
Error message missing cargo offset by the created delivery.

Sometimes i get an error of missing cargo as you can see in the second 

![image](https://user-images.githubusercontent.com/9070136/121208917-b7ca8400-c87a-11eb-9116-1e7e72c974af.png)
![image](https://user-images.githubusercontent.com/9070136/121208949-bdc06500-c87a-11eb-9d07-2f8008d02c3f.png)

in the first you can see that the content of the stop output is 2003 and in the second image the error for missing cargo because it expected 2013

the initial message for the created delivery also stated 2003

**Comment by raiguard** [comment]
LTNM shows whatever LTN gives it, so if LTN is throwing an incorrect alert, that's not on me.
