### ISSUE TITLE
LTN Manager button disabled on 1.1.35

### ISSUE THREAD

**Issue by libeks** [raiguard/Factorio-LtnManager#144]
I have a savefile that I've been working on for 85 hours. The LTN manager button is greyed out, i.e. disabled. This happened only after I upgraded to 1.1.35. The keyboard shortcut opens the Rich Text dialog.

<img width="230" alt="Screen Shot 2021-06-18 at 09 47 06" src="https://user-images.githubusercontent.com/2659165/122571726-061a1880-d01b-11eb-8134-80ca40f99e81.png">

**Comment by raiguard** [comment]
Type `/LtnManager refresh-player-data` in the console, then wait for a bit. That should fix it.

**Comment by libeks** [comment]
Thank you! That worked!
