### ISSUE TITLE
Icon for "GUI Unifyer" Mod

### ISSUE THREAD

**Issue by therock182** [raiguard/Factorio-LtnManager#145]
Hi,

it would be awesome if you could create a button in the top left corner for the ltn manager. i have to many shortcuts and too less place for them. If it´s possible it would be nice if you would cooperate with that mod "GUI Unifyer". Thanks

**Comment by raiguard** [comment]
GUI Unifier could easily use the [shortcut icon](https://github.com/raiguard/Factorio-LtnManager/blob/master/src/graphics/shortcut/ltn-manager-shortcut.png). It's about the right size.
