### ISSUE TITLE
LTN Manager does not unlock with Nullius

### ISSUE THREAD

**Issue by totobest** [raiguard/Factorio-LtnManager#147]
#### Describe the Bug

Nullius replaces/arranges most technologies, including some modded one like LTN.
I unlocked the LTN technologies but the manager cannot be opened.
I tried uninstalling/reinstalling manager.
![2021-11-10 16_56_39-Factorio 1 1 46](https://user-images.githubusercontent.com/11507846/141147958-83079af2-b812-4459-ae10-d566f2394895.png)

#### To Reproduce

1. Unlock LTN technology
2. Try to click on "LTN manager"
3. Nothing

#### Save file & Username

totobest

[14.zip](https://github.com/raiguard/Factorio-LtnManager/files/7514132/14.zip)

**Comment by raiguard** [comment]
Well, v0.4.0 appears to load just fine, so I'll count this as fixed for the next release.

**Comment by totobest** [comment]
Sorry to reopen it. I just upgraded to 0.4.6 and the issue still persists.

New save :
[16.zip](https://github.com/raiguard/Factorio-LtnManager/files/7598796/16.zip)
