### ISSUE TITLE
No longer able to focus on station from station list

### ISSUE THREAD

**Issue by jengo** [raiguard/Factorio-LtnManager#148]
#### Describe the Bug

Prior to 0.4.0 I was able to focus in on a station by clicking the station name in the station list.  This was very critical in debugging stations or finding stations that I forgot to label properly.

#### To Reproduce

Click stations -> hover over station, it only offers to open the station GUI not focus on the station.

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

https://www.transfernow.net/dl/202111163OJqJ4O5

Username: jengo1

#### Log file

This is a GUI issue with 0.4.0, broken (?) functionality,.  No errors in log

**Comment by raiguard** [comment]
I legitimately forgot about this feature, I will add it back in.
