### ISSUE TITLE
Crash on compare nil

### ISSUE THREAD

**Issue by neocult-de** [raiguard/Factorio-LtnManager#149]
#### Describe the Bug

LTN Manager 0.4.0 can crash if Train schedules are manipulated. Manually very rarely, but especially if using other mods modifying the train tables automatically like LTN Cleanup

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:541: attempt to compare nil with string
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:541: in function <__LtnManager__/scripts/ltn-data.lua:540>
	[C]: in function 'sort'
	__LtnManager__/scripts/ltn-data.lua:540: in function 'callback'
	__flib__/table.lua:233: in function <__flib__/table.lua:205>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:1073: in function 'iterate'
	__LtnManager__/control.lua:166: in function <__LtnManager__/control.lua:151>

#### To Reproduce

1. Use Trains in an LTN Network
2. Use LTN Cleanup Mod
3. Assign a Cleanup Station. 
4. A Train with leftover materials gets automatically reassigned to the Cleanup Station
5. The train arrives at the Cleanup Station (error message occurs (null comparison)

#### Save file & Username

[Recovery5.zip](https://github.com/raiguard/Factorio-LtnManager/files/7546337/Recovery5.zip)
Train in that savegame arrives after a moment.

Neocult is my ingame username. If you need any further info I can provide, let me know.

#### Log file

Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/7546342/factorio-current.log)

#### After Reinstalling Mods and Load the savegame I get a slightly different error:

Error while running event LtnManager::on_configuration_changed
__LtnManager__/scripts/player-data.lua:24: attempt to call method 'destroy' (a nil value)
stack traceback:
	__LtnManager__/scripts/player-data.lua:24: in function 'refresh'
	__LtnManager__/control.lua:61: in function <__LtnManager__/control.lua:53>

Alternate savegame without LTN Cleanup Mod, but with an already modified train table leading to the same crash (a few seconds after loading the savegame
[RecoveryTest6.zip](https://github.com/raiguard/Factorio-LtnManager/files/7546524/RecoveryTest6.zip)
)

**Comment by edsandrof** [comment]
Crash log:

```
O mod LTN Gerenciador (0.4.0) causou um erro não recuperável.
Por favor, reporte este erro ao autor do mod.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:541: attempt to compare nil with string
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:541: in function <__LtnManager__/scripts/ltn-data.lua:540>
	[C]: in function 'sort'
	__LtnManager__/scripts/ltn-data.lua:540: in function 'callback'
	__flib__/table.lua:233: in function <__flib__/table.lua:205>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:1073: in function 'iterate'
	__LtnManager__/control.lua:166: in function <__LtnManager__/control.lua:151>
```

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/7547765/factorio-current.log)

**Comment by blradlof** [comment]
I also received this same error when manually routing a train to a provider. It arrives at the station and begins to load, then crashes a few seconds later.

`The mod LTN Manager (0.4.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:541: attempt to compare string with nil
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:541: in function <__LtnManager__/scripts/ltn-data.lua:540>
	[C]: in function 'sort'
	__LtnManager__/scripts/ltn-data.lua:540: in function 'callback'
	__flib__/table.lua:233: in function <__flib__/table.lua:205>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:1073: in function 'iterate'
	__LtnManager__/control.lua:166: in function <__LtnManager__/control.lua:151>`

**Comment by JPLeo** [comment]
This just happened in my Krastorio game and a friend's Space Exploration game too
```
The mod LTN Manager (0.4.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:541: attempt to compare string with nil
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:541: in function <__LtnManager__/scripts/ltn-data.lua:540>
	[C]: in function 'sort'
	__LtnManager__/scripts/ltn-data.lua:540: in function 'callback'
	__flib__/table.lua:233: in function <__flib__/table.lua:205>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:1073: in function 'iterate'
	__LtnManager__/control.lua:166: in function <__LtnManager__/control.lua:151>
```

**Comment by raiguard** [comment]
Thanks for the report. Somehow, LTN is giving LTN Manager an item that doesn't exist (`steel-beam` in the case of the original report). This caused LTN Manager to crash because there is no translation for nonexistent items. I'm not sure why LTN is providing that nonexistent item, but it shouldn't crash any more (hopefully).

**Comment by neocult-de** [comment]
Thanks a lot. Everything back online (no issue on manual, automatic manipulation thanks to your check for null on empty/non existing). We are 5 Players and really enjoy your work. Great thanks!
