### ISSUE TITLE
Bad display of the content of a station

### ISSUE THREAD

**Issue by Telkine2018** [raiguard/Factorio-LtnManager#15]
Thank you for this great mod.

I have a problem with one of my game. In the list of station. one of the provider station "Iron 1" display the total inventory instead of its contents.

Here is a save of the game:

https://drive.google.com/open?id=1e1Z0ssUV0OYAL9p2HVBu3Izc4UMY0dvm

**Comment by avax87** [comment]
Hi, Raiguard!

I have the same problem. It seems that the first provider/requester (lowest station ID?) in every network ID displays the total contents of all providers/requesters in this network.

![LtnManagerBug1](https://user-images.githubusercontent.com/46025496/78997818-003fc200-7b50-11ea-8614-270c884eb226.PNG)

For example, i have 2 requesters in the network 524288. The first requests crushed stone, the seconds requests slag. But LtnManager displays that the first request both, while the second displayed ok.

The next 3 stations are providers. First provides slag, second - mineralized water, third - carbon dioxide. And again, LtnManger displays that the first provides all 3 sort of items.

Same issue with default network ID (-1). Not presented on screeshot.

P.S. I use Angel's and Bob's mods.

Thanks for your efforts!

**Comment by raiguard** [comment]
So, funny story... I was actually experiencing this bug the entire time that I was developing this mod, and even noticed it a few times, but put it off for "fixing later". I thought the cause would be really hard to pin down, but it was actually quite easy.

Anyway, fixed for the next release!
