### ISSUE TITLE
How to have train wait till station fills up to X amount ?

### ISSUE THREAD

**Issue by FluffyDiscord** [raiguard/Factorio-LtnManager#152]
Hi, can I make a Provider station and have Requesters actually wait till the Provider linked chests contain X amount of specific item that is needed ? I know I can do it with the vanilla "all * -1" trick, but can I also do it within your GUI and have it in one place ?

**Comment by raiguard** [comment]
LTN Manager doesn't allow you to modify your LTN setup, it is read only. If you need help with LTN itself, ask on the LTN thread on the Factorio forums.
