### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by dgattey** [raiguard/Factorio-LtnManager#154]
#### Describe the Bug
Looks like when filtered by a surface without depots, the missing depot translation is itself missing

![image](https://user-images.githubusercontent.com/982182/142299255-a3d1e513-2c1a-47cd-b949-ad8a67f3963b.png)

#### To Reproduce

Open up LTN Manager when there are no depots :) (for me, it's filtered onto a surface without depots)

#### Save file & Username

No save file attached since this is really just a basic change with translation!

**Comment by raiguard** [comment]
Thanks for the report, fixed for the next release.
