### ISSUE TITLE
Lost LTN Combinator integration

### ISSUE THREAD

**Issue by kryojenik** [raiguard/Factorio-LtnManager#156]
Looks like in the new revamp SHIFT-clicking on a station name take you to the map view of a station instead of opening the attached LTN Combinator.

Does it make sense to return the SHIFT-click behavior to opening the LTN Combinator and set CTRL-click to open the station in map view?

**Comment by raiguard** [comment]
The problem is, there are literally half a dozen different LTN combinator mods now. I can't support all of them.

**Comment by raiguard** [comment]
Sorry, this also slipped through the cracks during the rewrite.
