### ISSUE TITLE
Crash: LuaTrain API call when LuaTrain was invalid. Screenshot attached as imgur link at bottom.

### ISSUE THREAD

**Issue by lilcentaur2003** [raiguard/Factorio-LtnManager#157]
#### Describe the Bug

A crash occurs that Factorio seems to say is due to LTN Manager, at least as far as I can see from the description in the attached picture. 

#### To Reproduce

1. I have a large number of stations and a few trains. While doing nothing, an error pops up as shown in the image below.
I do have cargo ships enabled and I have 8 ports; 1 Oil drop off, 5 depots, and 2 ports near the deep sea oil pickups.

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

Upload the save file where the bug occured. If the file is too large for GitHub, use an alternative file service.
Save: https://ufile.io/vkv8xstp
Name: Lilcentaur

#### Log file

Log SHOULD be attached. If not, please let me know and I will do so. I've not used GH before.

Screenshot from crash: https://i.imgur.com/EB2YDvw.png

**Comment by raiguard** [comment]
I can't even load your save: it complains about a circular dependency:
![Screenshot_20211123_185017](https://user-images.githubusercontent.com/3515394/143156542-b9d2e18b-acb5-4d61-896b-de10e9d605a1.png)
Which is very odd.

**Comment by lilcentaur2003** [comment]
Strange. I've been loading in with no issues at all. I haven't messed with any of the files in either of those mods.

I reverted my LTN back to what it was before updating and the issue has gone away. I don't know how to fix the issue you are getting unfortunately.

**Comment by raiguard** [comment]
Strange indeed. Please let me know if you have any more issues!
