### ISSUE TITLE
Performance issues - Manual sync possible?

### ISSUE THREAD

**Issue by raven2k3** [raiguard/Factorio-LtnManager#158]
I love this mod because it gives you a good LTN overview, but currently LTN Manager 
causes some serious lagging on client side when it's installed on the server.

Lags are not network related, only client frame rate slows extremly down for 1 seconds every 2 seconds (UPS/FPS are still at 60!?).
After removing it the "lags" are gone.
Server has more than enough power and client renders 60 UPS all the time.

#### Is your feature request related to a problem? Please describe.

I just need the overview because without it's hard to use LTN - Is it possible to switch to a manual sync only?

#### Describe the solution you'd like

Option in the config to set refresh to manual like value '-1' or boolean toggle

#### Additional context
- Playing this with mod with Krastorio 2 Beta (1.2.3) + SE
- Already doubled LTN Manager Update values to increase performance.. no impact

**Comment by raiguard** [comment]
Increasing the LTNM value will make it slower, not faster. If you want better performance, decrease that value.

If you're having FPS issues, there's nothing I can do about that, you would have to ask the developers. LTNM does not do anything out of the ordinary when it comes to GUIs or sprites. Make sure you don't have auto-refresh enabled in the GUI just in case.

I might consider adding a manual sync, but it will affect all players, so its use will be recommended against.

**Comment by raiguard** [comment]
Are you still having this issue?
