### ISSUE TITLE
Crash while building mutiple stations 

### ISSUE THREAD

**Issue by GeneralTanker** [raiguard/Factorio-LtnManager#159]
#### Describe the Bug

While coping and pasting multiple stations the mod crashed. I don't know much of the other details. 

The mod LTN Manager (0.4.5) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
LtnManager/scripts/ltn-data.lua:626: bad argument #1 of 2 to 'lower' (string expected, got nil)
stack traceback:
    [C]: in function 'lower'
    LtnManager/scripts/ltn-data.lua:626: in function 'callback'
    flib/table.lua:233: in function <flib/table.lua:205>
    (...tail calls...)
    LtnManager/scripts/ltn-data.lua:1074: in function 'iterate'
    LtnManager/control.lua:172: in function <LtnManager/control.lua:157>

#### To Reproduce

1. The best way I can think of reproducing it is coping and pasting the same station (with the same name) a few times.

#### Save file & Username

Username: GeneralTank

Save file will be uploaded when I can make one with right scenario. The game crashed before I can make one. I am using the same mod pack (with some changes) as the one uploaded for recipe book.

#### Log file

[factorio-previous.log](https://github.com/raiguard/Factorio-LtnManager/files/7579063/factorio-previous.log)
.

**Comment by freezerain** [comment]
![image](https://user-images.githubusercontent.com/35431136/142948939-a40a1801-9c41-4663-b4dd-b1fb41a64a84.png)

Same error. As I said in closed ticket I have all my requester station with empty (space symbol " ") name. If you still think its a naming bug. Yet I didnt have that error before UI update last week

**Comment by freezerain** [comment]
small update, I almost sure I got this error 2 times some time after station deconstruct.

**Comment by raiguard** [comment]
Thanks for the report, fixed for the next release.

**Comment by raiguard** [comment]
I have been completely unable to reproduce it, but I found the one and only case where the station data couldn't have a name, and patched it. So hopefully it won't crash any more.

**Comment by GeneralTanker** [comment]
Hopefully it does this bug is very hard to reproduce.
