### ISSUE TITLE
Crash in Multiplayer

### ISSUE THREAD

**Issue by Blackclaws** [raiguard/Factorio-LtnManager#160]
#### To Reproduce

1. Have two players
2. LTN Manager takes a while to be accessible
3. Open it, sort trains
4. Crash

#### Log file
The mod LTN Manager (0.4.5) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_gui_checked_state_changed (ID 3)
__LtnManager__/scripts/gui/trains.lua:83: attempt to get length of local 'sorted_trains' (a nil value)
stack traceback:
	__LtnManager__/scripts/gui/trains.lua:83: in function 'update'
	__LtnManager__/scripts/gui/index.lua:131: in function 'update'
	__LtnManager__/scripts/gui/index.lua:97: in function 'dispatch'
	__LtnManager__/control.lua:80: in function 'handle_gui_event'
	__LtnManager__/control.lua:89: in function <__LtnManager__/control.lua:86>

**Comment by raiguard** [comment]
I cannot reproduce this. Could you please provide your save file?

**Comment by Blackclaws** [comment]
Here's the savegame:

https://drive.google.com/file/d/1UtLYQAp_nYGpuSU8-QtIS-8M0A8SZ78q/view?usp=sharing

Did not happen with users Blackclaws or Krymnopht, did happen once 3 people were in game for user Stromfresser once opening the GUI. He saw all trains being simply in state ERROR while we saw all trains doing fine.

I was thinking whether a clean reinstall would have fixed the issue however looking at the migrate function it should clean up anyway.

Let me know if we can help debug further, we're only playing Mondays though.

**Comment by raiguard** [comment]
Nice base! Unfortunately I still couldn't reproduce it. Honestly, I have no idea how this could even happen. That table should always exist, there is absolutely nothing that would delete it.

Please let me know if you encounter it again in your next play session. If not, then I'll close it.

**Comment by Blackclaws** [comment]
Thanks :D 

Yeah we'll do a clean install next time and see if that helps. We did go back to the 0.3x series for the time being because that didn't crash.

**Comment by raiguard** [comment]
Were you able to give it another shot?

**Comment by Blackclaws** [comment]
Just did on monday :) Seems fixed, whatever was causing the crashes no longer occurs. Thanks!
