### ISSUE TITLE
Crash while deleting the LTN station

### ISSUE THREAD

**Issue by luaotix** [raiguard/Factorio-LtnManager#162]
#### Describe the Bug

I am rebuilding the LTN station, building a new one and deleting the old one. But there seems to be some trains that didn't return to the old station, and then something went wrong.

#### To Reproduce

1. Delete stations where trains have not returned yet.
2. See error
3. The crash came suddenly, and I'm not sure if it's the real factor.

#### Save file & Username

https://drive.google.com/drive/folders/1wIP4Bv8gr9rw5cT42IwWQ7JAQmPP-JPC?usp=sharing

in-game username: asfoitio

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/7595905/factorio-current.log)

#### Crash report
Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:637: attempt to index field 'search_strings' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:637: in function 'callback'
	__flib__/table.lua:233: in function <__flib__/table.lua:205>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:1075: in function 'iterate'
__LtnManager__/control.lua:172: in function <__LtnManager__/control.lua:157>

I'm sorry to trouble you again, I didn't deliberately sabotage...
I really like this mod, thank you.

**Comment by H4nSolo** [comment]
Can Confirm this.
I have same Error Message

**Comment by raiguard** [comment]
How the flying frick is this even happening. This shouldn't be possible!

**Comment by H4nSolo** [comment]
Maybe try the following to understand the error:

- Create station for more than 5 trains with 4 wagons each
- Name every logistic stop in the train station with the same name (for example "TrainStation")
- Connect the stations with each other with a signal cable
- let a train enter the station
- dismantle the train ...
- Remove stops from the train station individually

From the 3rd station at the latest I always have the error message and the SaveGame crashes

**Comment by raiguard** [comment]
Yeah, I'll look at it tonight, I was just complaining because I thought I had guaranteed that that table existed, but apparently I didn't.

**Comment by raiguard** [comment]
Ok, took all of two seconds looking at the code before realizing the problem.

Now stations that are invalid are just completely removed from the stations table, instead of just being skipped. I'm pretty sure that was the original intent. We'll see if that causes problems, but I haven't been able to get it to crash... yet.
