### ISSUE TITLE
Hard crash when trying to use " [ " to search stations

### ISSUE THREAD

**Issue by FSynchro** [raiguard/Factorio-LtnManager#165]
#### Describe the Bug

Game crashes when entering a bracket to search for stations: [

#### To Reproduce

1. Open LTN Manager
2. Enter "[" In Search while having station window opened in LTN manager.
3. Crash

#### Save file & Username

I feel very confident this bug should be reproduce-able without my username and save; IE; See error message below.

Please also provide your in-game username so I can reproduce the conditions exactly.

Synchro

#### Log file
```
2785.426 Error ClientMultiplayerManager.cpp:98: MultiplayerManager failed: "The mod LTN Manager (0.4.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/gui/inventory.lua:49: malformed pattern (missing ']')
stack traceback:
	[C]: in function 'find'
	__LtnManager__/scripts/gui/inventory.lua:49: in function 'update_table'
	__LtnManager__/scripts/gui/inventory.lua:82: in function 'update'
	__LtnManager__/scripts/gui/index.lua:137: in function 'update'
	__LtnManager__/scripts/gui/index.lua:97: in function 'dispatch'
	__LtnManager__/control.lua:80: in function 'handle_gui_event'
	```

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/144772887-05edafd9-081c-4c43-8ebc-bc182c16130e.png)
Oops lol.
