### ISSUE TITLE
PLS, can you look what I made wrong with mod?

### ISSUE THREAD

**Issue by XpeHXpeH** [raiguard/Factorio-LtnManager#166]
Before 3-5 updates I can see  what station is in demand, o how many stations I have with resources, now not
https://imgur.com/a/VmnFlsV
https://imgur.com/a/SrRoujA
Thank you

**Comment by raiguard** [comment]
I'm not sure what the issue is. If you're talking about the material location lists that were on the inventory tab, they were removed because now you can search for materials on the stations tab to see which stations have them.

**Comment by XpeHXpeH** [comment]
* they were removed *, I understood. Thank you
