### ISSUE TITLE
Alerts list won't be repopulated after hitting the "Delete all Alerts" button

### ISSUE THREAD

**Issue by FSynchro** [raiguard/Factorio-LtnManager#167]
#### Describe the Bug

Whenever you have alerts within LTN, if you hit "delete all", new alerts will not populate the alerts window and the alerts number will remain [1] on the tab.

#### To Reproduce

1. Open LTN Manager
2. Click on 'Alerts (with active alerts)'
3. Hit "Delete all" at the very top right.
4. Have LTN throw a derp again (create another alert because oh no one of your trains left with cargo still in the hold.
5. Wonder where the alerts went.

#### Save file & Username

[Save is larger than 33MB]

I've poked you on Discord with the save (FSync#0001)

EDIT: https://cdn.discordapp.com/attachments/917944222080991252/917944337394978816/newangelsltnman.zip

Synchro

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/7672534/factorio-current.log)

**Comment by FSynchro** [comment]
Words of note: List won't be repopulated after a reboot, removing the mod and reinstalling it brings back this functionality again.

**Comment by nicolas-lang** [comment]
I have a similar Issue/contradiction:

![image](https://user-images.githubusercontent.com/635895/148253003-640aef70-c8e0-479c-bb07-a7a4d10f864b.png)

Alerts (3) 
No Alerts

**Comment by xor50** [comment]
Is that why I never have alerts in my list? Or does "train left with unexpected cargo" notification not count as an alert?
