### ISSUE TITLE
Error inside data-manager.iterate_data()

### ISSUE THREAD

**Issue by Ethrel** [raiguard/Factorio-LtnManager#17]
```
Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/data-manager.lua:460: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__LtnManager__/scripts/data-manager.lua:463: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
```

Solution seems to be a nil check on global.working_data.alert_popups. Edited my local copy to:
```LUA
    -- create alert popups
    if global.working_data.alert_popups == nil then
      global.working_data.alert_popups = {};
    end
    for _,t in pairs(global.working_data.alert_popups) do
      alert_popup_gui.create_for_all(t)
    end
```
which seems to solve the problem. I don't know if there is a deeper underlaying issue elsewhere and this is just a mask.

**Comment by raiguard** [comment]
Could you send me your save file or find a way to reproduce it from a new file?

**Comment by raiguard** [comment]
Oh, you were the one who was using this pre-alpha. This table didn't exist until right before I released the alpha, that's why you're having issues. Completely remove the mod from your save (disable the mod, load your save, save it, then re-enable the mod and load again) and this issue should go away.

**Comment by raiguard** [comment]
Well, I was flat-out wrong. I'll apply the fix that you suggested until I can find out the actual problem. I apologize!
