### ISSUE TITLE
LuaEntity API call when LuaEntity was invalid

### ISSUE THREAD

**Issue by Quezler** [raiguard/Factorio-LtnManager#171]
#### Describe the Bug

![Screen Shot 2021-12-31 at 14 59 29](https://user-images.githubusercontent.com/3179271/147827129-21e878ae-d01f-4c31-ae89-9ed330c8ea9f.png)

#### To Reproduce

1. honestly not sure, the modpack contains space exploration so perhaps players using the satelites to visit other planets?
2. i don't expect it to happen again, but when it does i'll try to narrow it down, feels a bit one-off atm
3. the crash does happen again when you load the save though

#### Save file & Username

[`Quezler`](http://83.137.145.42/ltn-manager-crash.zip)

#### Log file

```
9802.158 Error MainLoop.cpp:1284: Exception at tick 20016045: The mod LTN Manager (0.4.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__LtnManager__/scripts/ltn-data.lua:760: in function '?'
	__LtnManager__/scripts/ltn-data.lua:1074: in function 'iterate'
	__LtnManager__/control.lua:175: in function <__LtnManager__/control.lua:160>
9802.159 Error ServerMultiplayerManager.cpp:91: MultiplayerManager failed: "The mod LTN Manager (0.4.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__LtnManager__/scripts/ltn-data.lua:760: in function '?'
	__LtnManager__/scripts/ltn-data.lua:1074: in function 'iterate'
	__LtnManager__/control.lua:175: in function <__LtnManager__/control.lua:160>"
9802.159 Info ServerMultiplayerManager.cpp:797: updateTick(20016045) changing state from(InGame) to(Failed)
9802.174 Quitting: multiplayer error.
9803.323 Info ServerMultiplayerManager.cpp:140: Quitting multiplayer connection.
9803.324 Info ServerMultiplayerManager.cpp:797: updateTick(4294967295) changing state from(Failed) to(Closed)
```
update 1:
- crash happened again, seemingly when a player changed surface via rocket, no one had the ltn gui open a the time
- some trains were actively hauling oil from an oil planet to its sender rocket while said player was using a rocket

update 2:
-  entry.surface_index = train.main_locomotive.surface.index possibly has the same cause as https://github.com/raiguard/Factorio-LtnManager/commit/e9dc7ac26e5857d656a58188827e1b96b255babc
- biters are constantly attacking trains, but we're also using recursive blueprints to demolish returning trains at the ltn depos

update 3:
- 3rd ~~times~~ crash the charm, just gonna remove this mod for now, regrettably since i really like the overview it gives 😢

**Comment by raiguard** [comment]
Were you beta testing the Space Elevator when this happened?

**Comment by raiguard** [comment]
Actually, this is closely related to #168, which I have fixed for the next version.

**Comment by Quezler** [comment]
no, i was playing only with versions obtained from the mod portal

my guess is that it might have had something to do with trains getting destroyed or deconstructed right as it tries to write history
