### ISSUE TITLE
"This shortcut requires the LTN Technology" -  LTN is already researched.

### ISSUE THREAD

**Issue by Galapagon** [raiguard/Factorio-LtnManager#174]
I am unable to open the LTN Manager via the shortcut and receive the message in the title when trying to add it to my quick bar, even though LTN is already researched.
I am however, able to use CTRL+T to open the menu, however the hotbar option remains unavailable.
I also tried /LtnManager refresh-player-data but nothing changed after several minutes.

Here is my full mod List:
    alien-biomes
    angelspetrochem
    angelsrefining
    angelssmelting
    AutoTrash
    boblibrary
    boblogistics
    botReplacer
    BottleneckLite
    copy-recipe-to-chest
    CredoTimeLapseModByGalapagon
    DiscoScience
    even-distribution
    factoryplanner
    flib
    FNEI
    LogisticTrainNetwork
    LtnManager
    LTN_Combinator_Modernized
    ModuleInserter
    nullius
    OutpostPlanner1-1
    PlannerCore1-1
    RateCalculator
    SchallSatelliteController
    Squeak Through
    Todo-List
    trainsaver

**Comment by raiguard** [comment]
Have you built an LTN station yet? It doesn't unlock until you do.

**Comment by Galapagon** [comment]
I had over 100 existing LTN stations before adding the mod, however to be sure I manually placed another with my character (ie no bots) but the hotbar icon is still unavailable.

**Comment by raiguard** [comment]
Could you please upload your save file?

**Comment by Galapagon** [comment]
I can do that later today, it's also available in public servers as "community... Oct/Nov" if you'd like to connect to the live environment/create a save

**Comment by Galapagon** [comment]
[OctNov Community map.zip](https://github.com/raiguard/Factorio-LtnManager/files/7825569/OctNov.Community.map.zip)
Sorry for the delay

**Comment by raiguard** [comment]
Unfortunately I cannot reproduce this. If you can reproduce it on the lastest version of Factorio and your mod list, please upload the save file again and I'll see what I can find. Apologies for the delay.
