### ISSUE TITLE
Crash on LTN Manager 0.4.9

### ISSUE THREAD

**Issue by dgattey** [raiguard/Factorio-LtnManager#177]
#### Describe the Bug

Getting an error while in the Editor Extensions lab surface:

```
Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:1023: attempt to index field '?' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:1023: in function '?'
	__LtnManager__/scripts/ltn-data.lua:1076: in function 'iterate'
	__LtnManager__/control.lua:165: in function <__LtnManager__/control.lua:150>
```

EDIT: It actually appears to be happening if you just wait for about two minutes or so on the save I uploaded. No jumping to the other surface needed.

#### To Reproduce

~1. Jump into the lab surface created automatically by Editor Extensions (click the button in the shortcuts area of the toolbar)~
2. Wait until LTN Manager tries to update (under a minute for my settings)
3. Crashes

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

https://www.dropbox.com/s/647cijo27p73k4a/save.zip?dl=0 is the save, username is dgattey

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/8020262/factorio-current.log)

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/156096397-bb9610d2-a33b-47b7-b6ca-fc12ea5a4d68.png)
Heh, apparently I already knew about this issue.
