### ISSUE TITLE
Error on load after update from 0.1.0 to 0.1.3

### ISSUE THREAD

**Issue by Tukamok** [raiguard/Factorio-LtnManager#20]
This popped up shortly after loading a saved game after updating to 0.1.3.

The mod LTN Manager [ALPHA] (0.1.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/data-manager.lua:446: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__LtnManager__/scripts/data-manager.lua:446: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>

**Comment by raiguard** [comment]
Huh... interesting. Someone else reported this issue but I couldn't get it to happen. Guess I'll just band-aid it. I'll release a patch shortly.

**Comment by raiguard** [comment]
I released a patch forever ago that should have fixed this.
