### ISSUE TITLE
Game crashes after selecting "Stations" tab

### ISSUE THREAD

**Issue by Astorin** [raiguard/Factorio-LtnManager#21]
I'm playng vanilla+Krastorio2.
Game crashes after selecting "Stations" tab.

Error dump:

 151.083 Script @__RaiLuaLib__/lualib/event.lua:365: Tried to disable conditional event 'gui.depots.depot_button.on_gui_click', which is not enabled!
 178.807 Error MainLoop.cpp:1202: Exception at tick 13939008: Мод LTN Менеджер [АЛЬФА] (0.1.3) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event LtnManager::on_gui_click (ID 1)
Unknown sprite "ltnm_indicator_signal-X"
stack traceback:
	__RaiLuaLib__/lualib/gui.lua:110: in function 'recursive_build'
	__RaiLuaLib__/lualib/gui.lua:168: in function 'recursive_build'
	__RaiLuaLib__/lualib/gui.lua:208: in function 'build'
	__LtnManager__/gui/stations.lua:80: in function 'update'
	__LtnManager__/gui/main.lua:267: in function 'update'
	__LtnManager__/gui/main.lua:286: in function 'update_active_tab'
	__LtnManager__/gui/main.lua:57: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
stack traceback:
	[C]: in function 'add'
	__RaiLuaLib__/lualib/gui.lua:110: in function 'recursive_build'
	__RaiLuaLib__/lualib/gui.lua:168: in function 'recursive_build'
	__RaiLuaLib__/lualib/gui.lua:208: in function 'build'
	__LtnManager__/gui/stations.lua:80: in function 'update'
	__LtnManager__/gui/main.lua:267: in function 'update'
	__LtnManager__/gui/main.lua:286: in function 'update_active_tab'
	__LtnManager__/gui/main.lua:57: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>

**Comment by raiguard** [comment]
Could you please send me your save file?

**Comment by Astorin** [comment]
Here the save
[Krastorio 2.zip](https://github.com/raiguard/Factorio-LtnManager/files/4463552/Krastorio.2.zip)

**Comment by raiguard** [comment]
Thanks. That's strange... this is a very odd issue. I'll see what I can do.

**Comment by Hadramal** [comment]
If it helps, I have the exact same issue but do NOT run Krastorio 2.

**Comment by raiguard** [comment]
Thanks, fixed for the next version.
