### ISSUE TITLE
"Open LTN Manager" button

### ISSUE THREAD

**Issue by Astorin** [raiguard/Factorio-LtnManager#22]
Hello.
Add the "Open LTN Manager" button on the screen.
Hotkey is not convenient for everyone.

**Comment by raiguard** [comment]
There is a shortcut for it on the shortcut bar:
![image](https://user-images.githubusercontent.com/3515394/79026607-9ec72580-7b46-11ea-96fa-e499cf5bfdce.png)
If it's not there by default you can enable it in the shortcut bar configurator.

**Comment by KayEss** [comment]
I was about to log a bug as I thought that the UI button was missing due to running Krastario 2 or Helmod.

Can you at least put something in the README so that people can find the way to open it? Given that you're not using the same way that people are used to from LTN tracker.

**Comment by raiguard** [comment]
LTN Manager 1.0 beta did this same thing. Regardless, I will put something on the mod page about it.

**Comment by KayEss** [comment]
Thanks. It's just to help users. Now I know how to see it, it looks really good. Looking forwards to using it in anger!
