### ISSUE TITLE
Way to filter stations tab

### ISSUE THREAD

**Issue by jarquafelmu** [raiguard/Factorio-LtnManager#23]
I would love a way to search or filter the stations tab. Like a search field that can search on station name and only show stations with a similar matching name or a way to only see requesters or only see providers, things like that that can help me to drill down more what is being handled at my stations

**Comment by jarquafelmu** [comment]
It would also be nice to have a features template in addition to the bug report template

**Comment by raiguard** [comment]
Sure, I'll create a feature template.

**Comment by raiguard** [comment]
As for the feature request, I was always planning on adding filtering by name and network ID, but filtering by provider/requester is also a good idea. So thank you!

**Comment by jarquafelmu** [comment]
I know that inventory sort of has filtering by item but it would be nice if the station list had a way to filter by item even if that's just by using the name.

Also being able to filter which stations / trains are generating errors having have the stations have a indicator of how many errors involve them

also a tab to see all of your LTN trains

:D

**Comment by raiguard** [comment]
The depots tab is what shows you the trains. I was looking into adding a dedicated "shipments" tab that would show you all active shipments but decided it was better left until people had given me feedback on the current design. The current design is very much based on LTN Tracker but is open for changes.

I do plan on adding more options to the alerts tab, but that won't be a for a while probably.

Filtering by shipment is redundant,  that's what the inventory screen is for. Click the item and it'll show you all the stations that are providing or requesting that item.

**Comment by Yousei9** [comment]
Filtering stations by network is quite important. It's the easiest, for beginners only, way to find misconfigured stops.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/82092279-32e05b80-96b6-11ea-93a5-44daf0063518.png)

The stations tab can now be searched by both station name and network ID. The search is _very slow_ at the moment, but is fully functional! Performance improvements will come later in the alpha process.
