### ISSUE TITLE
Features/enhancement reporting template

### ISSUE THREAD

**Issue by jarquafelmu** [raiguard/Factorio-LtnManager#24]
It would be nice to have a feature reporting template in addition to the bug report template. This way feature requests / ideas can structurally look similar to help with identifying what is being asked and making it easier on users to supply ideas for features

**Comment by raiguard** [comment]
Just added one :D

**Comment by raiguard** [comment]
I've never had this much activity on a repository before so I didn't think to set up the templates before releasing the alpha.
