### ISSUE TITLE
Error on deleting a scheduled train

### ISSUE THREAD

**Issue by avax87** [raiguard/Factorio-LtnManager#27]
Hi!

**Describe the bug**
When train is scheduled for delivery, LTNManager triggers a crash when you try to delete this train.

**Save file**
My game is heavily modded, if you'll be unable to reproduce it, i can try to reproduce it without other mods and provide a save.

**To Reproduce**
1. Start a new sandbox game
2. Create depot, provider and requester stations and configure it
3. Wait for train to be scheduled for delivery
4. Delete this train

**P.S. it seems that this bug happens only with a new game.**

Error log:
```
The mod LTN Manager [ALPHA] (0.1.4) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/gui/alert-popup.lua:73: attempt to index field 'settings' (a nil value)
stack traceback:
	__LtnManager__/gui/alert-popup.lua:73: in function 'create_for_all'
	__LtnManager__/scripts/data-manager.lua:452: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>

**Comment by jarquafelmu** [comment]
Provide a save anyways. It helps so that the author can see what is happening exactly

**Comment by raiguard** [comment]
Saves are nice, but if you can consistently reproduce it from new saves, it's probably not required. It would generally be a good idea to upload one anyway, just in case. I'll update the issue template with that information.

**Comment by raiguard** [comment]
Turns out I forgot to sync player settings on first join. I never noticed this because every time I tested, I added the mod to an existing LTN demo world. Thank you for the report!
