### ISSUE TITLE
Way to filter history tab

### ISSUE THREAD

**Issue by jarquafelmu** [raiguard/Factorio-LtnManager#28]
**Is your feature request related to a problem? Please describe.**
I would like to look at my history tab to verify if a station is getting resources sometimes. How it is right now I have to go hunting to find what I am looking for.

**Describe the solution you'd like**
A search field in the filter tab

**Additional context**
A global search bar would be fine, just the left of the pin, refresh, and close buttons

**Comment by raiguard** [comment]
A global search bar in the header is something I never thought about, and is a good idea! I'll see what I can come up with. Thanks!

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/82163643-b2faf280-9869-11ea-8636-a1197ea575f4.png)

In for the next version!
