### ISSUE TITLE
0.1.7 breaks Construction Drones mod

### ISSUE THREAD

**Issue by xmirakulix** [raiguard/Factorio-LtnManager#30]
Version 0.1.7 breaks the Construction Drones mod.
Drones don't get sent out as soon as LTN-Manager is updated to 0.1.7.

Works with 0.1.6 and Rai's Lua Lib 0.2.5

To reproduce:
- Place entity ghost
- Wait for drones to get sent out

I would very much like to debug further, but I lack the fundamental knowledge of the tools around factorio modding.

Save is attached
[_autosave3.zip](https://github.com/raiguard/Factorio-LtnManager/files/4466484/_autosave3.zip)

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/79075576-ef5a9200-7cb0-11ea-9153-d4036530f87d.png)
It works just fine for me...

**Comment by xmirakulix** [comment]
Confirmed, sorry for the false alarm.
I tried it several times back and forth before opening the issue.

The only thing that has changed now is, that I redownloaded 0.1.7.
Why this should matter is beyond me though...
