### ISSUE TITLE
crash in 0.1.7, table index is nil

### ISSUE THREAD

**Issue by xmirakulix** [raiguard/Factorio-LtnManager#31]
See screenshot, not sure how to reproduce, sorry.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/425180/79115029-14203980-7d85-11ea-8e9b-05e23908015a.png">

Do you need more?

**Comment by xmirakulix** [comment]
Probably has something to do with temporary stops, not sure...

**Comment by jarquafelmu** [comment]
Attach a save file and does this happen when you create a temporary stop?

**Comment by raiguard** [comment]
Yes, please attach a save file, otherwise debugging this will be much harder. :)

**Comment by xmirakulix** [comment]
Sorry, I seem to have lost the specific save and I am unfortunately unable to reproduce the bug. Feel free to close as irreproducible...

**Comment by raiguard** [comment]
No problem. If it happens again, please let me know!
