### ISSUE TITLE
Alerts - Spacing of buttons on larger alerts needs to be to the top like single spaced alerts

### ISSUE THREAD

**Issue by distraughtmonkey** [raiguard/Factorio-LtnManager#33]
**Describe the bug**
Spacing of buttons on larger alerts needs to be to the top like single spaced alerts

**Save file**
Upload the save file where the bug occured. If the file is too large for GitHub, use a file service such as Google Drive or Dropbox. If these aren't available, PM me (Raiguard) on the Factorio forums, or on Discord (Raiguard#7402).

If you can consistently reproduce the error from a new save, please upload the original save anyways, just in case.

**To Reproduce**
1. Go to 'Alerts'
2. Click on 'Delete Alert'
![factorio_2020-04-13_18-52-55](https://user-images.githubusercontent.com/3711672/79177719-5e6ede00-7db8-11ea-8b6e-782b6e9b8875.png)

**Comment by raiguard** [comment]
Thanks for the feedback, but this is not a bug. It is designed that way on purpose. Aligning it to the top would leave an even larger space on the bottom, which would look even worse.

**Comment by distraughtmonkey** [comment]
Thanks Raiguard, It's not so much about look, its about having to move the mouse up and down each time the spacing changes so you cannot clear the messages quickly. As the larger spacing takes the top slot you can no longer continue clicking but must move the mouse down...then back up...then back down...etc.

**Comment by raiguard** [comment]
Ah, I see! I didn't think about that. I'm planning on adding a clear all alerts button, which will solve that issue.

**Comment by distraughtmonkey** [comment]
Beauty! Thanks Raiguard!
