### ISSUE TITLE
Multiplayer causes non-recoverable error

### ISSUE THREAD

**Issue by whiskerdreams** [raiguard/Factorio-LtnManager#34]
**Describe the bug**
A clear and concise description of what the bug is. If the bug was a crash, include a screenshot or a copy of the crash text.

Brought up multiplayer mode with no problem.  Everything works but when another player joins the server it generates a non-recoverable error.  I captured a screen print of the error dialog box.
```
Please report this error to the mod author.

Error while running event LtnManager::on_player_joined_game (ID 43)
__RaiLuaLib__/lualib/translation.lua:168: attempt to index local 'player_data' (a nil value)
stack traceback:
	__RaiLuaLib__/lualib/translation.lua:168: in function 'start'
	__LtnManager__/control.lua:56: in function 'run_player_translations'
	__LtnManager__/control.lua:180: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
2412.932 Error ServerMultiplayerManager.cpp:90: MultiplayerManager failed: "The mod LTN Manager [ALPHA] (0.1.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_player_joined_game (ID 43)
__RaiLuaLib__/lualib/translation.lua:168: attempt to index local 'player_data' (a nil value)
stack traceback:
	__RaiLuaLib__/lualib/translation.lua:168: in function 'start'
	__LtnManager__/control.lua:56: in function 'run_player_translations'
	__LtnManager__/control.lua:180: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>"
```

**Save file**
Upload the save file where the bug occured. If the file is too large for GitHub, use a file service such as Google Drive or Dropbox. If these aren't available, PM me (Raiguard) on the Factorio forums, or on Discord (Raiguard#7402).

https://drive.google.com/file/d/19-_sup-KoY3iLLcMxDXaj6PBTxi9tJ4A/view?usp=sharing

If you can consistently reproduce the error from a new save, please upload the original save anyways, just in case.

**To Reproduce**
1. Multiplayer - Load Save File (LAN only)
2. Have other player join and immediately after catching up factorio crashes.

It also happened in 0.1.6

Thanks!

**Comment by raiguard** [comment]
I don't get the bug when following your steps. Are you on the latest version of RaiLuaLib? This looks like a bug that I fixed in the most recent version of that mod.

**Comment by whiskerdreams** [comment]
This little thing.  It's currently sustaining around 2.5k spm.  Trying to reach goal of 5k spm.  I checked and my RuaLuaLib is at 0.2.5 which on the site is the latest and greatest.  I will ask the other person to check his mod list to be sure he's on the same version too.

I hope we can find this.  It's very hard to identify shortcomings on the map without your mod to get inside what's happening, what's running short and where it's going to.  Great Mod!  I love it!

**Comment by whiskerdreams** [comment]
I just uploaded a new version of the save file. This ones got the satellite and silo array started and functional.  Same link as above.

**Comment by whiskerdreams** [comment]
Raiguard,

I finally got to try this with the other guy and we are both on RaiLuaLib 0.2.5 but had the same result.

Thanks

**Comment by raiguard** [comment]
I just released a RaiLuaLib update that should hopefully fix this issue.

**Comment by whiskerdreams** [comment]
This fixed the problem.  We were able to multi-player and not crash... :)
