### ISSUE TITLE
crash when opening ltn UI

### ISSUE THREAD

**Issue by JanEggers** [raiguard/Factorio-LtnManager#35]
I updated mods and now I get this when opening the ltn manager ui

![image](https://user-images.githubusercontent.com/6747376/79192540-2f448500-7e29-11ea-9fc9-170d20ceeef5.png)

**Comment by raiguard** [comment]
As explained in the bug report template, please upload your save file. I cannot debug the issue nearly as easily without a save file.

**Comment by JanEggers** [comment]
[kastorio 2.zip](https://github.com/raiguard/Factorio-LtnManager/files/4480868/kastorio.2.zip)

**Comment by raiguard** [comment]
I cannot reproduce this error. However, it looks like you somehow opened the GUI before it had time to retranslate all of your dictionaries and add sorting data for you. Try running the `/LtnManager refresh_player_data` command, wait for the shortcut to be available again, and see if that fixes it.

**Comment by JanEggers** [comment]
hmm it worked for me now also without running the command.

I disabled it because i tend to forget it was broken and used it anyway crashing the game. maybe i can break it again and post a save where the ui is in the shorcut bar and broken.

**Comment by raiguard** [comment]
Huh, interesting. Well, please let me know if it happens again!
