### ISSUE TITLE
Gui exception in alert

### ISSUE THREAD

**Issue by whiskerdreams** [raiguard/Factorio-LtnManager#37]
**Describe the bug**
Was trying to investigate an alert about a delivery timeout and when I clicked on the destination station that was on the left it crashed with the following exception.

56162.070 Error MainLoop.cpp:1202: Exception at tick 187163626: The mod LTN Manager [ALPHA] (0.1.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_gui_click (ID 1)
__LtnManager__/gui/main.lua:116: attempt to index field '?' (a nil value)
stack traceback:
	__LtnManager__/gui/main.lua:116: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>

**Save file**
It's the same save file as before.

https://drive.google.com/open?id=19-_sup-KoY3iLLcMxDXaj6PBTxi9tJ4A

I tried to duplicate the error on another alert but it did not cause the exception.  The only difference between them that I can discern is that the exception was on a station that was randomly named and the non-exception station was renamed by me.

Funny thing when I went back to try and find the un-named station I couldn't find it.  It didn't exist on the map?

Thanks Again!  Loving this mod!

**Comment by raiguard** [comment]
I have an idea of why this happened, but I'm not going to fix it for today's patch. The fix will be in the next one.

**Comment by whiskerdreams** [comment]
Would this also happen if the name of the station changed between cycles?  I could see that as being the problem because when I loaded the map again and went back to find the errant unnamed station I couldn't find it.

**Comment by raiguard** [comment]
I can reproduce this exact error on the same line by removing the station, then clicking on its name. So that must be what happened.

I also tested changing the station's name, but that didn't cause a crash.

Thank you for the report, I'll fix this soon!
