### ISSUE TITLE
View element gaz in tab stations and inventory

### ISSUE THREAD

**Issue by dairen** [raiguard/Factorio-LtnManager#38]
**Describe the bug**
i can to see oil, acid... but gaz is not showing in tabs station and inventory
in tab inventory, we can see the requesting but not the providing

**Save file**
N/A

If you can consistently reproduce the error from a new save, please upload the original save anyways, just in case.

**To Reproduce**
add a provider with gaz
i use the same conf for oil, gaz and acid

![image](https://user-images.githubusercontent.com/3027708/79358569-a79e6980-7f41-11ea-8317-0a597ee3e8ce.png)

**Comment by dairen** [comment]
water too by the way

**Comment by raiguard** [comment]
Assuming you're talking about petroleum gas, I have no such issue. Please check your LTN setup to make sure it's actually being provided correctly.

In the future, please always check your LTN setup before posting what you think are bugs. This mod is meant to do exactly that - help you find issues!

![image](https://user-images.githubusercontent.com/3515394/79505081-1981bc00-7ff1-11ea-80a6-31c70aa9b66e.png)

![image](https://user-images.githubusercontent.com/3515394/79505099-1f779d00-7ff1-11ea-9cb6-263098660568.png)

**Comment by dairen** [comment]
how to explain that I use the same configuration for acid oil and ltn works to provide and request acid oil gas or water with train

If you want to refer in your config to define a bug free for you

**Comment by raiguard** [comment]
Could you send me your save file then?

**Comment by dairen** [comment]
i can if you want but this evenning, i can  see water and gas

**Comment by raiguard** [comment]
Oh, so it's fixed now? Awesome!
