### ISSUE TITLE
Incompatibility with latest LTN version

### ISSUE THREAD

**Issue by raiguard** [raiguard/Factorio-LtnManager#39]
The latest LTN version has, at my request, standardized the names of API information to match Factorio's scheme. This will break LTN Manager significantly. An update will be out later today.

I'm making this issue so nobody reports it as a bug. Sit tight for a few hours and I'll have a patch out!

**Comment by raiguard** [comment]
**UPDATE:** the patch has been released. I will close this issue tomorrow morning.

**Comment by aoakeley** [comment]
I'm getting the lamp_control nil index error on multiplayer but not single player using LTN 1.13.1 and LTNManager 0.1.8 (same game save)

re:
2020/04/17 07:26:47 Factorio Server: Error while running event LtnManager::on_tick (ID 0)
2020/04/17 07:26:47 Factorio Server: __LtnManager__/scripts/data-manager.lua:64: attempt to index field 'lamp_control' (a nil value)
2020/04/17 07:26:47 Factorio Server: stack traceback:
2020/04/17 07:26:47 Factorio Server:    __LtnManager__/scripts/data-manager.lua:64: in function 'iterate_stations'
2020/04/17 07:26:47 Factorio Server:    __LtnManager__/scripts/data-manager.lua:412: in function 'handler'
2020/04/17 07:26:47 Factorio Server:    __RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>

save: https://www.dropbox.com/s/29yx2udpv7w7ovd/Autosaved%20Recover%20NEW.zip?dl=0

**Comment by raiguard** [comment]
Got it... I forgot to add code to reset the LTN data iteration when mod configuration changes. It was trying to process data given by the previous version of LTN. So now, it'll completely stop iterating data and reset when mod configuration changes.

An update will be out shortly with the fix!
