### ISSUE TITLE
AAAANd - Crash ;)

### ISSUE THREAD

**Issue by NetTecture** [raiguard/Factorio-LtnManager#41]
Update to latest version, manager and LTN. Map Runs a minute r two, then crashes (without any related ation from me, I am just leaving it running doing some watching).

Error whle running event LogisticsTrainNetwork:on_train_changed_state(ID 23)
__LtnManager__/scripts/dataManager.lua:588 attempt to perform arithmetic on field "started" (a nil value)
__LtnManager__/scripts/data-manager.lua:588 in function Whandler"
__RailLuaLib__/lualib/event.lua:127

**Comment by raiguard** [comment]
As stated in the template... _please_ send me the save file. :)

**Comment by raiguard** [comment]
I can't fix the bug unless you send me the save file where the bug occured!

**Comment by raiguard** [comment]
Please send me a save file so I can fix this!
