### ISSUE TITLE
Disable Alert Box (Red Box)

### ISSUE THREAD

**Issue by cbassett1000** [raiguard/Factorio-LtnManager#42]
Some way to disable the Red alert box popping up in view either in manager view or settings.

Furthermore, disable certain alerts.  For example, I don't want the see incorrect pickup because my coal train picked up way more than it was supposed to. (I know it's my fault but have higher priorities than fixing it)

**Comment by raiguard** [comment]
There is already a setting to disable the popups, it's a per-player setting in the mod settings menu. ;)

As for disabling certain alerts, I'll add that.

**Comment by schoos76** [comment]
In case you need an idea what to disable: I currently would love to see a feature to disable the "incorrect pickup" alert for small differences with liquid pickups - maybe make a threshold configureable?

**Comment by raiguard** [comment]
Disabling certain alerts will still happen at some point, but I'm closing this issue since its main question was solved.
