### ISSUE TITLE
crash when load krastorio 2 save after last update

### ISSUE THREAD

**Issue by gardziej** [raiguard/Factorio-LtnManager#43]
**Describe the bug**
`The mod LTN Manager [ALPHA] (0.1.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__RaiLuaLib__/lualib/translation.lua:49: attempt to index local 'pt' (a nil value)
stack traceback:
	__RaiLuaLib__/lualib/translation.lua:49: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>`

**Save file**
75mb, but i can upload it somewhere if needed

**Comment by raiguard** [comment]
Please upload your save file to Google Drive or somewhere, then send me a link.

**Comment by raiguard** [comment]
Nevermind, someone else reported this as well, and I fixed it. The issue was with RaiLuaLib, there is an update out now for that mod.
