### ISSUE TITLE
Linux Headless Server Crash

### ISSUE THREAD

**Issue by yofreak** [raiguard/Factorio-LtnManager#46]
**Describe the bug**
The game crashes at connecting to the server. with mod version 0.17 an 0.18

![LTN 1](https://user-images.githubusercontent.com/253581/79636181-2ed42300-8176-11ea-998b-2d61ac170f23.jpg)
![LTN 2](https://user-images.githubusercontent.com/253581/79636183-2f6cb980-8176-11ea-9903-7200b2ee5255.jpg)

**Save file**
Upload the save file where the bug occured. If the file is too large for GitHub, use a file service such as Google Drive or Dropbox. If these aren't available, PM me (Raiguard) on the Factorio forums, or on Discord (Raiguard#7402).

https://1drv.ms/u/s!Arzhmf6o8KiomBR-xq-PQqG0SrmM?e=jBM1rr

If you can consistently reproduce the error from a new save, please upload the original save anyways, just in case.

**To Reproduce**

Start a headless server with all mods on version 0.18.18 and try to connect

**Comment by raiguard** [comment]
You need to update LTN to 1.13.1.
