### ISSUE TITLE
LTN Manager [ALPHA] (0.1.9) caused a non-recoverable error

### ISSUE THREAD

**Issue by Spud80** [raiguard/Factorio-LtnManager#47]
Thanks a lot for fixing the previous issue in 0.1.8. I had an issue with that one as well.

Just tried the new update 0.1.9, and we ran into another issue. It's from an old save with many mods and no previous usage of LTN Manager (just the old LTN/LTN Tracker on factorio 0.17.xx). However, it was a bit concerning seeing this.

**Error description (station tab)**
```
The mod LTN Manager [ALPHA] (0.1.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_gui_click (ID 1)
__LtnManager__/gui/stations.lua:137: attempt to concatenate field '?' (a nil value)
stack traceback:
	__LtnManager__/gui/stations.lua:137: in function 'update'
	__LtnManager__/gui/main.lua:281: in function 'update'
	__LtnManager__/gui/main.lua:300: in function 'update_active_tab'
	__LtnManager__/gui/main.lua:57: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
```

**Second error (inventory tab):**
```
The mod LTN Manager [ALPHA] (0.1.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_gui_click (ID 1)
__LtnManager__/gui/inventory.lua:145: attempt to concatenate field '?' (a nil value)
stack traceback:
	__LtnManager__/gui/inventory.lua:145: in function 'update'
	__LtnManager__/gui/main.lua:281: in function 'update'
	__LtnManager__/gui/main.lua:300: in function 'update_active_tab'
	__LtnManager__/gui/main.lua:57: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
```

**Save file**
https://drive.google.com/open?id=1Hl2qHaJTmhMlwmbiMOcaX-tT00pYoe5O

**To Reproduce**
1. Click CTRL + T
2. Go to inventory or station tab
3. Error

**Comment by raiguard** [comment]
Thanks for actually following the bug report template! Most people don't do that, and it's infuriating.

However, I don't have permission to access the drive link. Could you please make it public so I can download it? Thanks!

**Comment by Spud80** [comment]
Forgot to set permissions to public. Sorry. Link in original post updated as well:
https://drive.google.com/open?id=1Hl2qHaJTmhMlwmbiMOcaX-tT00pYoe5O

**Comment by raiguard** [comment]
Oh boy... Industrial Revolution. Guess I'll have to download it and patch it myself.

**Comment by raiguard** [comment]
Could you try running the `/LtnManager refresh_player_data` command and see if that fixes it? The error is happening because some materials are missing translations... apparently.

**Comment by Spud80** [comment]
No. It did not help. Tried the refresh commandCrashed again when selecting the Station tab.

The mod LTN Manager [ALPHA] (0.1.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_gui_click (ID 1)
__LtnManager__/gui/stations.lua:137: attempt to concatenate field '?' (a nil value)
stack traceback:
	__LtnManager__/gui/stations.lua:137: in function 'update'
	__LtnManager__/gui/main.lua:281: in function 'update'
	__LtnManager__/gui/main.lua:300: in function 'update_active_tab'
	__LtnManager__/gui/main.lua:57: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>

The Industrial Revolution mod has a heck of a lot of items, so I should suspect it was that one creating problems. I don't use this Mod my self any more (older save), so I don't care that much. But I thought it was a good idea to look into the problem in case it was a more widespread problem.

**Comment by raiguard** [comment]
So I got around to downloading IR and patching it to work on 0.18, and I cannot reproduce this error. The problems seem like they're stemming from missing translations, which should be flat-out impossible.

What I'm going to do is check for missing translations and use the internal name instead. If you see any non-localised names in 0.1.10, please let me know!

**Comment by raiguard** [comment]
The patch is out, please let me know if you run across any untranslated names!
