### ISSUE TITLE
Mouse scroll works inconsistently

### ISSUE THREAD

**Issue by danyax** [raiguard/Factorio-LtnManager#49]
Inventory tab, right pane - mouse wheel scroll works only when cursor is over light grey background, when cursor is over station content row (dark grey) scroll is not working

**Comment by raiguard** [comment]
There isn't really anything I can do about this, that's base game behavior. However, it will be fixed as a side effect when I improve that page's styling, which will happen sometime in the future. So I'll keep this issue open.

**Comment by raiguard** [comment]
I have fixed this issue for the next version. Now the scroll panes will only be active when actually needed, which is not very much of the time.
