### ISSUE TITLE
Add sorting by station signals

### ISSUE THREAD

**Issue by danyax** [raiguard/Factorio-LtnManager#51]
Please add sorting by station control signals (compare them as character string). I have few hundreds of stations, sorting will help to debug wrong signaling of stations - if list is sorted, I can easily detect any inconsistency in signals.

**Comment by raiguard** [comment]
In for v0.4.0.

![image](https://user-images.githubusercontent.com/3515394/95691030-35010480-0bd9-11eb-9fa8-e89bb73e782c.png)
