### ISSUE TITLE
Add option to define control signal column width

### ISSUE THREAD

**Issue by danyax** [raiguard/Factorio-LtnManager#53]
Station tab - column "Control signal" has width for 4 signal. All my station has from 5 to 8 signals, so each station takes 2 rows. Combined with small window size it is a real pain to scroll through hundred of stations.

**Comment by raiguard** [comment]
Unfortunately this just isn't likely to happen. The GUI needs to have a hardcoded width so I can make everything line up properly, due to Factorio's limited GUI API. I'm sorry!
