### ISSUE TITLE
Improve station opening UI

### ISSUE THREAD

**Issue by danyax** [raiguard/Factorio-LtnManager#54]
LTN Tracker had 2 useful features - 1) draw red circle around selected station on the map view - helps a lot when many stations are packed close by 2) an option to open station UI when showing station on map.

**Comment by raiguard** [comment]
I'll add this for v0.2.0.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/82271906-56b1d480-9936-11ea-9f16-895ea41e480a.png)
The station will now have a circle drawn around it when you view it.
