### ISSUE TITLE
LTN Manager GUI does not open

### ISSUE THREAD

**Issue by nicolas-lang** [raiguard/Factorio-LtnManager#56]
Thanks for the mod, I have heard a lot of positive stuff about it...  hope to be able to use it myself soon..

**Describe the bug**
When playing Factorio (0.18.19) with LTN 1.13.1 and LtnManager 0.1.9 I have issues opening the GUI.
- The message I receive is "_Cannot open LTN Manager yet Either translations are not yet finished or LTN hasn't send any data_"
- This happens independent of using Button or Shortcut. (Button is grayed-out)
- The behavior is not consistent, as sometimes I have been able to open the GUI ( like 5% of times when I tried it)
- The Issue happens when playing locally and on a dedicated server.
- A Friend of mine can access the GUI most times (in the same game)

Related to the issue I have found this in the server's log files
```
 172.343 Script @__RaiLuaLib__/lualib/translation.lua:249: Canceling translation of [materials] for player [Karoschel]
 172.344 Script @__RaiLuaLib__/lualib/translation.lua:249: Canceling translation of [gui] for player [Karoschel]
```
**Save file**
Providing a save file is slightly troublesome as I am using an unpublished custom warehouse mod, and without warehouses LTN would just not work ... If it helps: https://cloud.bnslang.de/index.php/s/pGSb3QYZZ5YRYN6 (File expires on 01.05.2020)

**To Reproduce**
1. Start the map
2. Hit LTN Manager Button
3. Nothing happens
4. Wait 30s 
5. try again
6. Nothing happens

**Comment by raiguard** [comment]
Try running `/LtnManager refresh_player_data`, wait a bit, and see if the button lights up and becomes clickable.

**Comment by nicolas-lang** [comment]
Yes, that worked. - I'll play a bit and check if it stays working.

**Comment by raiguard** [comment]
It should stay working forever now, until you add/remove/update any mods. Then it'll retranslate everything for everyone again.

**Comment by Panderine** [comment]
I'm having this same issue now with 0.18.28

**Comment by raiguard** [comment]
What language are you running, and could you please send a save file?

**Comment by Panderine** [comment]
English. Here is the [save](https://we.tl/t-Au4YEnhVau) It was working before in the same game for and my other player. Thanks for your time!

**Comment by raiguard** [comment]
Further discussion will happen over on #75.
