### ISSUE TITLE
Alerts are not easy to read

### ISSUE THREAD

**Issue by jarquafelmu** [raiguard/Factorio-LtnManager#6]
The small alert with the red background and black text is heard to read for me at least, maybe a darker red background with a lighter font?

![image](https://user-images.githubusercontent.com/5807272/78951557-c9a27280-7a8f-11ea-90c6-4bc437f238ca.png)

**Comment by raiguard** [comment]
I'm going to add support for the "classic GUI" mod that will include things like this. Thank you for your feedback!

**Comment by raiguard** [comment]
These popups are going away in v0.3, so I'm closing this.
