### ISSUE TITLE
The value for the requested is not shown.

### ISSUE THREAD

**Issue by Androix777** [raiguard/Factorio-LtnManager#64]
I’m not sure that this is a problem of this mod, but the value of the requested resource shows only positive values. Maybe I am using LTN incorrectly, but I usually set a positive treshold, and a negative maximum resource value. For example, 15,000 a treshold request and - 30,000 of the required resource means that I need a maximum of 30,000 resources at the station and it must be delivered if more than 15,000 are missing. I connect this to my chests. Thus, for almost all stations, I do not get any value for the requested value, since they are almost always negative. How can I solve this problem?

**Comment by raiguard** [comment]
Please provide a save file, as stated in the bug report template.

**Comment by Androix777** [comment]
Save file - [mainPy.zip](https://github.com/raiguard/Factorio-LtnManager/files/4611832/mainPy.zip)
I don’t think that this is a bug, but rather my misunderstanding of how the mod should work, so I did not add a bug label. There is no forum or discussion page on the mod page, so I wrote it here.
