### ISSUE TITLE
Ability to clear all alerts

### ISSUE THREAD

**Issue by maxtimbo** [raiguard/Factorio-LtnManager#65]
**Is your feature request related to a problem? Please describe.**
I turned off alerts from LTN Manager a while back. But I've recently wanted to start debugging my network. The Issue is that when I open LTN Manager to see Alert Report, my game comes to a grinding halt. I would like the ability to clear all alerts and deal with them a little more slowly.

**Describe the solution you'd like**
Add a button to clear alerts

**Additional context**

**Comment by raiguard** [comment]
Duplicate of #60. Thanks!
