### ISSUE TITLE
Depot Occupancy Rate

### ISSUE THREAD

**Issue by PGScully** [raiguard/Factorio-LtnManager#67]
**Is your feature request related to a problem? Please describe.**
I'd like to know which depots are heavily utilized, which continually have few or no trains sitting idle, and need more trains added.

**Describe the solution you'd like**
One way this could be achieved is a graph in the depot's overview showing the number of in use and idle trains over time.

**Comment by raiguard** [comment]
I'll add this to the backlog. A graph definitely won't happen unless the devs add graphs as a moddable GUI element.

**Comment by raiguard** [comment]
I have received word from the developers that moddable graphs just aren't going to happen. Sorry!
