### ISSUE TITLE
LTN Manager Crash after deconstructing Train Stop

### ISSUE THREAD

**Issue by nicolas-lang** [raiguard/Factorio-LtnManager#69]
**Describe the bug**
While playing factorio a "non-recoverable error" occured with LTN-Manager

> 
> 38258.727 Error MainLoop.cpp:1205: Exception at tick 38528685: The mod LTN Manager [ALPHA] (0.1.10) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event LtnManager::on_lua_shortcut (ID 34)
> LuaEntity API call when LuaEntity was invalid.
> stack traceback:
>         __LtnManager__/gui/stations.lua:83: in function 'update'
>         __LtnManager__/gui/main.lua:280: in function 'update'
>         __LtnManager__/gui/main.lua:299: in function 'update_active_tab'
>         __LtnManager__/gui/main.lua:304: in function 'open'
>         __LtnManager__/gui/main.lua:330: in function 'toggle'
>         __LtnManager__/control.lua:195: in function 'handler'
>         __RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
> stack traceback:
>         [C]: in function '__index'
>         __LtnManager__/gui/stations.lua:83: in function 'update'
>         __LtnManager__/gui/main.lua:280: in function 'update'
>         __LtnManager__/gui/main.lua:299: in function 'update_active_tab'
>         __LtnManager__/gui/main.lua:304: in function 'open'
>         __LtnManager__/gui/main.lua:330: in function 'toggle'
>         __LtnManager__/control.lua:195: in function 'handler'
>         __RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>

**Save:**
save not available at the moment, sorry.

**Events leading to the Crash:**
1. Cut & Paste of a Train stop Provider (Deconstructed and rebuilt)
2. Open GUI

**Comment by raiguard** [comment]
Does this still occur on the most recent version?

**Comment by nicolas-lang** [comment]
i'm still on 18.26 / 0.1.10 due to some other mod incompatibilities, i'll post an update when i am on the most recent version again

**Comment by raiguard** [comment]
I was about to ask you if it still happens, but you're among those who couldn't open it after the update. So I guess I'll have to delay this fix.

**Comment by raiguard** [comment]
Could you test this again and see if you can reproduce it?

**Comment by raiguard** [comment]
Are you still able to reproduce this issue?

**Comment by raiguard** [comment]
Closing due to lack of response.
