### ISSUE TITLE
0.18.27 alert error

### ISSUE THREAD

**Issue by nlubisch** [raiguard/Factorio-LtnManager#70]
**Describe the bug**
I updated to the new version 0.18.27 today - after i got the first alert and clicked it this error appears
It's reproducable with my state of the game.

![image](https://user-images.githubusercontent.com/3511228/82953991-21e3f400-9fac-11ea-90cd-0575bd4b352e.png)

**Save file**
https://drive.google.com/open?id=19gyeVFYcnrDB0HFwkcwrUBiQmH8pFXDh

**To Reproduce**
1. Open the save game
2. Wait some time until the alert appears
3. Click it => error

**Comment by raiguard** [comment]
Thank you, this has been fixed for the next version.
