### ISSUE TITLE
LTNManager crashes on load

### ISSUE THREAD

**Issue by maxtimbo** [raiguard/Factorio-LtnManager#71]
**Describe the bug**
Crash on load

**Save file**
Upload the save file where the bug occured. If the file is too large for GitHub, use a file service such as Google Drive or Dropbox. If these aren't available, PM me (Raiguard) on the Factorio forums, or on Discord (Raiguard#7402).

If you can consistently reproduce the error from a new save, please upload the original save anyways, just in case.

**To Reproduce**

![image](https://user-images.githubusercontent.com/8702833/83095873-4acebc80-a072-11ea-96e7-79511c690fc3.png)

**Comment by raiguard** [comment]
This is actually a bug with LTN Combinator, not LTN Manager.
