### ISSUE TITLE
Crash open Stations

### ISSUE THREAD

**Issue by Michael11056** [raiguard/Factorio-LtnManager#72]
**Describe the bug**
Crash on Open Stations

**Save file**
[Michi-02-Exp.zip](https://github.com/raiguard/Factorio-LtnManager/files/4693133/Michi-02-Exp.zip)

![image](https://user-images.githubusercontent.com/36220431/83097179-c303a500-a0a7-11ea-9508-23dbb086373b.png)

**To Reproduce**
Open Stations

**Comment by Soggs** [comment]
`566.600 Error ServerMultiplayerManager.cpp:90: MultiplayerManager failed: "The mod LTN Manager [ALPHA] (0.2.1) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event LtnManager::on_gui_click (ID 1)
Unknown style deep_frame_in_shallow_frame_no_left
stack traceback:
__LtnManager__/scripts/gui/main-tabs/stations.lua:183: in function 'update'
__LtnManager__/scripts/gui/main.lua:328: in function 'update'
__LtnManager__/scripts/gui/main.lua:355: in function 'update_active_tab'
__LtnManager__/scripts/gui/main.lua:49: in function 'handler'
__flib__/gui.lua:349: in function 'dispatch_handlers'
__flib__/gui.lua:135: in function <__flib__/gui.lua:135>
stack traceback:
[C]: in function '__newindex'
__LtnManager__/scripts/gui/main-tabs/stations.lua:183: in function 'update'
__LtnManager__/scripts/gui/main.lua:328: in function 'update'
__LtnManager__/scripts/gui/main.lua:355: in function 'update_active_tab'
__LtnManager__/scripts/gui/main.lua:49: in function 'handler'
__flib__/gui.lua:349: in function 'dispatch_handlers'
__flib__/gui.lua:135: in function <__flib__/gui.lua:135>"
566.600 Info ServerMultiplayerManager.cpp:771: updateTick(6800382) changing state from(InGame) to(Failed)`

Same here.

**Comment by raiguard** [comment]
Geez... I really am dumb.

Ill have a fix out later today. Sorry!
