### ISSUE TITLE
Crash on startup - v. 0.2.2 on Factorio 0.18.28

### ISSUE THREAD

**Issue by Ratmaniak** [raiguard/Factorio-LtnManager#74]
Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/gui/main-tabs/depots.lua:173: bad argument #1 of 2 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	__LtnManager__/scripts/gui/main-tabs/depots.lua:173: in function 'update'
	__LtnManager__/scripts/gui/main.lua:328: in function 'update'
	__LtnManager__/scripts/gui/main.lua:355: in function 'update_active_tab'
	__LtnManager__/scripts/gui/main.lua:282: in function 'create'
	__LtnManager__/control.lua:171: in function <__LtnManager__/control.lua:157>

**Comment by Ratmaniak** [comment]
Actually, it seems to be an incompatability with LTN 1.13.7. 
Regressing to 1.13.6 resolves the error.

**Comment by Soggs** [comment]
Same bug. Map actually loaded on the server and one player (me) was able to join. Then crashed as the second player did catch up.

235.056 Error MainLoop.cpp:1205: Exception at tick 8043775: The mod LTN Manager [ALPHA] (0.2.2) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/gui/main-tabs/depots.lua:173: bad argument #1 of 2 to 'ipairs' (table expected, got nil)
stack traceback:
[C]: in function 'ipairs'
__LtnManager__/scripts/gui/main-tabs/depots.lua:173: in function 'update'
__LtnManager__/scripts/gui/main.lua:328: in function 'update'
__LtnManager__/scripts/gui/main.lua:355: in function 'update_active_tab'
__LtnManager__/scripts/gui/main.lua:282: in function 'create'
__LtnManager__/control.lua:171: in function <__LtnManager__/control.lua:157>
235.056 Error ServerMultiplayerManager.cpp:90: MultiplayerManager failed: "The mod LTN Manager [ALPHA] (0.2.2) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/gui/main-tabs/depots.lua:173: bad argument #1 of 2 to 'ipairs' (table expected, got nil)
stack traceback:
[C]: in function 'ipairs'
__LtnManager__/scripts/gui/main-tabs/depots.lua:173: in function 'update'
__LtnManager__/scripts/gui/main.lua:328: in function 'update'
__LtnManager__/scripts/gui/main.lua:355: in function 'update_active_tab'
__LtnManager__/scripts/gui/main.lua:282: in function 'create'
__LtnManager__/control.lua:171: in function <__LtnManager__/control.lua:157>"
235.056 Info ServerMultiplayerManager.cpp:771: updateTick(8043775) changing state from(InGame) to(Failed)

**Comment by raiguard** [comment]
Both of you _please_ send me save files. I cannot debug this issue without a save file!

**Comment by Soggs** [comment]
https://drive.google.com/file/d/1rQXroNxpEepTMeijB3xqo0nl0qK3fbHm/view?usp=sharing

**Comment by raiguard** [comment]
I cannot reproduce this crash... odd.

Try removing the mod from your save then adding it again?

**Comment by Panderine** [comment]
I have the same error now after manually patching with your fix for my previous error (Reset LTN iteration flags on config changed (#75))

**Comment by Soggs** [comment]
After readding it to the save there were no more crashes in yesterdays session but for some reason I had the bug mentioned in #75 but others were able to use the manager perfectly fine.

**Comment by Panderine** [comment]
Can confirm that removing the mod from the save and re adding it with the fixes from #75 solve all issues.

**Comment by raiguard** [comment]
So, I managed to reproduce it once, but I have absolutely no clue as to how it happened. Since it's no longer crashing for either of you, I'll consider it case closed until it happens again.

**Comment by raiguard** [comment]
So, I finally managed to reproduce it, and I'm pretty sure that this is a side effect of another issue that I fixed. I'll be releasing a new version later tonight, please give it a go and let me know if the issue comes up again!
