### ISSUE TITLE
LTN Manager GUI does not open

### ISSUE THREAD

**Issue by Panderine** [raiguard/Factorio-LtnManager#75]
Same as [https://github.com/raiguard/Factorio-LtnManager/issues/56](url) but running the mentioned command doesn't fix it. 

The message I receive is "Cannot open LTN Manager yet Either translations are not yet finished or LTN hasn't send any data"

I'm having this same issue with 0.18.28 (worked fine before). On the server's logs I don't see anything. Having this issue as well in a fresh local new gameplay.

LTN v1.13.8

**Comment by raiguard** [comment]
Thanks for the report, this has been fixed for the next release.

**Comment by dbeckwith** [comment]
I'm having the same issue, the command from #56 did not seem to do anything.

**Comment by nicolas-lang** [comment]
This issue reappeared for me at version 0.2.2 with the /LtnManager refresh_player_data not helping.
The other command /retranslate-all-dictionaries just disappeared ( and with 0.2.0 I had to call it manually  every session)
--> No way for me to use LTN Manager at the moment

**Comment by raiguard** [comment]
For everyone having issues: I forgot that I changed the command to `refresh-player-data`, with dashes instead of underscores, in v0.2.0. Please try that and see if it helps!

**Comment by nicolas-lang** [comment]
I have no feedback of "/LtnManager refresh-player-data" doing anything and the button stays gray

**Comment by Aderol** [comment]
Please help with this problem, I need this mod :c
The commands above did not help (

**Comment by dbeckwith** [comment]
Still not working for me as well

**Comment by raiguard** [comment]
I apologize to everyone having this issue, I have been super busy / distracted. I will make time to look at this tonight.

If everyone who is experiencing this could send me their save file, that would greatly aid in my finding and fixing this issue.

**Comment by suisseWalter** [comment]
Here is my file: [https://drive.google.com/file/d/1Vo-cgMvgoW66fLppO1eeZ1dl12ElwlzE/view?usp=sharing](https://drive.google.com/file/d/1Vo-cgMvgoW66fLppO1eeZ1dl12ElwlzE/view?usp=sharing) 
don't be surprised if it looks like a mess, I removed some overhaul mods as some files had to be modified to even work. but the error consists even with all of them removed.

**Comment by nicolas-lang** [comment]
https://www.dropbox.com/s/9j170bxnx9pplu1/K2-SE_LTN-Manager-Debug.zip?dl=1
A couple of custom/non-public mods in this save but that can't be helped at the moment.

**Comment by dbeckwith** [comment]
Here is my save: https://www.dropbox.com/s/3gcplb09bcrjjay/krastorio2.tar.gz?dl=0
I also included the whole mods folder since I have a few patched mods

**Comment by raiguard** [comment]
So, please don't hate me...

I fixed this eighteen days ago! I'm just an idiot and never pushed the fixed version. I even _said_ that I fixed it in this issue!

Obviously I wasn't paying any attention. I'll have the patch out later today, alongside some other bug fixes.

**Comment by raiguard** [comment]
All of you who provided save files, thanks! But I don't actually need them after all...

**Comment by nicolas-lang** [comment]
<3 no worries

**Comment by raiguard** [comment]
I'm going to close this to make sure I remember that it's fixed :D
