### ISSUE TITLE
Clicking the Depot Tab while no trains at all are in the network seems to crash the game.

### ISSUE THREAD

**Issue by Soggs** [raiguard/Factorio-LtnManager#77]
I guess somebody clicked the Depot Tab while there where no depots or no depots with any trains assigned.

16602.716 Error MainLoop.cpp:1205: Exception at tick 991358: The mod LTN Manager [ALPHA] (0.2.2) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:206: table index is nil
stack traceback:
__LtnManager__/scripts/ltn-data.lua:206: in function 'sort_depot_trains'
__LtnManager__/scripts/ltn-data.lua:445: in function 'iterate'
__LtnManager__/control.lua:161: in function <__LtnManager__/control.lua:157>
16602.716 Error ServerMultiplayerManager.cpp:90: MultiplayerManager failed: "The mod LTN Manager [ALPHA] (0.2.2) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:206: table index is nil
stack traceback:
__LtnManager__/scripts/ltn-data.lua:206: in function 'sort_depot_trains'
__LtnManager__/scripts/ltn-data.lua:445: in function 'iterate'
__LtnManager__/control.lua:161: in function <__LtnManager__/control.lua:157>"
16602.716 Info ServerMultiplayerManager.cpp:771: updateTick(991358) changing state from(InGame) to(Failed)

**Save file**
[E.18.30-SE-2020-06-03-recovery.zip](https://github.com/raiguard/Factorio-LtnManager/files/4726370/E.18.30-SE-2020-06-03-recovery.zip)

**Log file**
[factorio-current20200603214319.log](https://github.com/raiguard/Factorio-LtnManager/files/4726368/factorio-current20200603214319.log)

**Comment by raiguard** [comment]
I'm unable to reproduce this error. Does it happen consistently?

**Comment by Soggs** [comment]
I removed the mod because multiplayer and also the error did not happen directly to me. It was just what I got from the users online at the time.

I can throw the save on one of our servers for testing purposes.

**Comment by raiguard** [comment]
That would be appreciated. No matter how hard I try I can't get it to crash!

**Comment by raiguard** [comment]
So, I managed to reproduce it. The crash is happening because there are several missing translations in your player data table. I actually have no idea how that could be the case, but simply updating to a new version should fix it (updating causes all translations to be re-done).

If the issue persists after updating, please let me know!
