### ISSUE TITLE
Integration with LTN Combinator

### ISSUE THREAD

**Issue by binarycow** [raiguard/Factorio-LtnManager#78]
LTN Tracker had an integration with the LTN Combinator mod.  If an LTN combinator was attached to the LTN stop, then you could view and change the settings on the LTN Combinator from the LTN Tracker UI.

I suggest that you add this feature to LTN Manager.

**Comment by raiguard** [comment]
This is already in. Shift+click the station's name.

**Comment by binarycow** [comment]
Hmm... that doesn't seem to do the same thing.  Shift clicking the station name just takes me to the map view of the station.  LTN Tracker opened the combinator UI for the LTN combinator, without going to map view.

**Comment by raiguard** [comment]
Are you on the most recent version? It should tell you how to do it when you hover the station. I just tested it and it works fine.

![image](https://user-images.githubusercontent.com/3515394/83929600-344ef200-a751-11ea-95e1-fab7a7f2bf3e.png)

**Comment by binarycow** [comment]
Ah.  Perhaps that's it.  I am on 0.1.10.  I **thought** I was up to date because it doesn't show in the "Updates" tab.  But... I am running Factorio version 0.18.21, because a lot of mods broke on 0.18.22, and I haven't tested them on 0.18.22 yet.  I see that the latest version has a dependency on a more current version of Factorio.

Thanks for your help, sorry about the confusion!
