### ISSUE TITLE
On GUI Click

### ISSUE THREAD

**Issue by artolva** [raiguard/Factorio-LtnManager#79]
Had this error occur twice since migrating from 0.18.26 to 0.18.30.

Reloading a save doesn't immediately reproduce the issue due to the time discrepancy, it seems to be a unique state problem when the GUI is clicked.

![image](https://user-images.githubusercontent.com/48080677/83993392-a5cbb200-a996-11ea-8724-06f9c57e9739.png)

**Comment by raiguard** [comment]
PLEASE send me your save file. I don't get why people keep ignoring this VERY CLEAR instruction in the bug report template!

**Comment by artolva** [comment]
Sorry mate, file was too big for github.

Uploaded to WeTransfer - https://we.tl/t-TkavnQfNxV

**Comment by raiguard** [comment]
Are you still getting this error? I cannot reproduce it.

**Comment by raiguard** [comment]
I was unable to reproduce this issue. Please let me know if it happens again!
