### ISSUE TITLE
Long Trains cause "Composition" column in Depots tab to run into next column

### ISSUE THREAD

**Issue by Inveli** [raiguard/Factorio-LtnManager#8]
I tested with a depot for 4-8 trains. The text in the composition column is longer that the column, and it runs into the Train Status text, appearing behind it.

![Capture](https://user-images.githubusercontent.com/63441826/78967601-8c0e0b80-7ac8-11ea-8a96-36f46098bacb.PNG)

**Comment by raiguard** [comment]
See #9, this has been fixed
