### ISSUE TITLE
Very high CPU consumption

### ISSUE THREAD

**Issue by danyax** [raiguard/Factorio-LtnManager#81]
I run large A&B megabase with few hundreds stations and 120 trains. I did run LTNTracker for long time and now finally switched to new LTN version and LTN Manager. While generally all runs good I have one problem that nearly kills my UPS. My base run with average 30ms update time. But roughly every 30 sec LTN Manager starts to consume huge amount of update time, starting from 1ms, going up to 10ms and even more then gradually resetting back to close to zero, something like bell curve. It happens every 30 seconds. All other time LTN Manager consumes very little time. 

Any idea how to fix it? I can upload save file with mod pack, if it helps you.

**Comment by raiguard** [comment]
The logic surrounding LTN Manager is not particularly optimized yet. That's why I still consider it an alpha. I plan on reworking the logic to spread out all of it over multiple ticks to mitigate the performance drops.
