### ISSUE TITLE
Allow filtering of Network IDs

### ISSUE THREAD

**Issue by PiggyWhiskey** [raiguard/Factorio-LtnManager#82]
In the GUI it doesn't look possible to filter or sort by Network IDs.

To check which network a station is, you need to go through all the icons on the right of the GUI to find the Network icon.

A sortable column could solve this, or a text/integer bar at the top to select the Network.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/84603538-67c60680-ae4c-11ea-8894-6d244d915ec0.png)
You can filter by network ID in the search bar.

**Comment by PiggyWhiskey** [comment]
My GUI seems a little different to yours:
Depot:
![image](https://user-images.githubusercontent.com/9373995/84624155-ff485980-af1f-11ea-9df8-87be100c8b69.png)
Stations:
![image](https://user-images.githubusercontent.com/9373995/84624168-0707fe00-af20-11ea-858a-016fa0eaa888.png)
Inventory:
![image](https://user-images.githubusercontent.com/9373995/84624179-0cfddf00-af20-11ea-8ce3-1affe0b6e87c.png)
History:
![image](https://user-images.githubusercontent.com/9373995/84624189-125b2980-af20-11ea-8084-883a734e3c52.png)
Alerts:
![image](https://user-images.githubusercontent.com/9373995/84624200-17b87400-af20-11ea-97a8-5063d91cab95.png)


None of the tabs have anything above it.

Maybe notable, I also don't have the LTN Manager button at the top of the screen.
![image](https://user-images.githubusercontent.com/9373995/84624269-3454ac00-af20-11ea-99d4-faba9d568656.png)

Double checked that I had the latest version (0.2.2)

**Comment by raiguard** [comment]
You need to click the search button... I even had that in my screenshot.

There is no button at the top of the screen on purpose. There is a button on the shortcut bar so there is no reason to have one at the top as well.
