### ISSUE TITLE
Allow 'Keep Open' to work when selecting Trains/Stations

### ISSUE THREAD

**Issue by PiggyWhiskey** [raiguard/Factorio-LtnManager#83]
When selecting Trains or Stations from the LTN Manager GUI, it closes the GUI and doesn't re-open after closing the train GUI or for Stations exiting Map mode.

Is it possible to automatically re-open the GUI after closing those actions?

**Comment by raiguard** [comment]
If you have keep-open enabled (the pin icon next to the refresh button) the GUI will stay open. If you don't it will close.

There are many ways the map could be closed again, which means many edge cases. I don't have plans to change the behavior.
