### ISSUE TITLE
Error while running event LtnManager::on_tick (ID 0) - Different error location than Issue #80

### ISSUE THREAD

**Issue by PiggyWhiskey** [raiguard/Factorio-LtnManager#84]
I was building a large Depot with Bots.
During Construction or Construction this would randomly occur. 

![image](https://user-images.githubusercontent.com/9373995/84584530-ae176780-ae44-11ea-9e2e-f5f7555d46c8.png)

This is the game during the crash (I was using CTRL Z to undo the deconstruction)
![image](https://user-images.githubusercontent.com/9373995/84584543-c6878200-ae44-11ea-85e2-f8ee128e6a09.png)

I could intermittently reproduce it, but once I saved the game (To provide a precise test point) it stopped happening.

I created a second Issue as the Lua line is different to #80

**Comment by PiggyWhiskey** [comment]
[2020 2.zip](https://github.com/raiguard/Factorio-LtnManager/files/4776311/2020.2.zip)
The error occurs in this save within 2-3 seconds of loading.

**Comment by raiguard** [comment]
Yes, thanks for creating a separate issue, since this is a completely different problem! I will look into it.

**Comment by raiguard** [comment]
Thanks for the report, this is fixed for the next release, coming tonight!
