### ISSUE TITLE
Cannot open LTN Manager yet..

### ISSUE THREAD

**Issue by mtomsovic** [raiguard/Factorio-LtnManager#85]
"Cannot open LTN Manager Yet.  Either translations are not yet finished or LTN hasn't sent any data."

This seems to have broken out of the blue, it was working yesterday.  The last thing I did was added about 15 new LTN stations part of a new network ID.  There's almost 200 trains on the default/standard network ID.

I went around and changed the network ID to the default on all new stations and am still seeing the problem.

Suggestions on what I can check?

**Comment by raiguard** [comment]
Could you send me your save file? After doing that, try running `/LtnManager refresh-player-data` in your console. Wait a moment and see if the button becomes clickable again.

The button won't enable until all translations have been sorted and LTN has sent data. The more mods you have, the longer this will take. Also be sure that LTN actually _is_ sending data.

**Comment by mtomsovic** [comment]
Thanks for the quick response!

Unfortunately, the console command doesn't seem to help/do anything.  

LTN Trains are still picking up and delivering things normally.  How can I verify that it actually is sending data correctly?

I use only a few mods:

- LTN Combinator
- LTN Content Reader
- LogisticTrainNetwork
- LTN Manager
- Some-Zoom

**Comment by raiguard** [comment]
I'm going to need the save file, unfortunately. Could you upload it to Google Drive or Dropbox, then post a link?

**Comment by nicolas-lang** [comment]
After the update the button was still greyed-out but executing `/LtnManager refresh-player-data` resolved this for now.

**Comment by mtomsovic** [comment]
I can confirm that after the update things work properly again.  

I needed to wait a minute for LTN to update a cycle before the UI enabled, but it did so without me needing to issue any console commands.

Thanks for the quick fix!

**Comment by Neovik78** [comment]
We ware still having this Problem in Multiplayer with the new Version
on the Host it is working but on the client it is always showing this error message
should it work in multiplayer ?

**Comment by raiguard** [comment]
Yes, it should work just fine. @Neovik78 could you please send me the save file so I can take a look?

Also, did you try running the command?

**Comment by Neovik78** [comment]
thanks after update of the mod and running the command it worked 
thanks very much for the great mod

**Comment by raiguard** [comment]
Awesome!
