### ISSUE TITLE
Train content misaligned in inventory tab

### ISSUE THREAD

**Issue by xmirakulix** [raiguard/Factorio-LtnManager#87]
#### Describe the Bug

Train contents in inventory tab seem to be aligned to the right, causes misalignment on long station names, see image.

<img width="827" alt="Screenshot" src="https://user-images.githubusercontent.com/425180/85055125-63c41c80-b19d-11ea-9634-03dcad782799.png">

Tell me if a savegame is really needed.

**Comment by raiguard** [comment]
Geez, that's a long station name, I would recommend shortening it.

I'll fix this in v0.3, which will have some other GUI improvements.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/93533038-639ffe00-f8ff-11ea-8e87-3190a70fb85f.png)

At long last, this is fixed for the next release.
