### ISSUE TITLE
Search doesn't cancel on ESC

### ISSUE THREAD

**Issue by xmirakulix** [raiguard/Factorio-LtnManager#88]
#### Describe the Bug

A search in e.g. the station tab is not canceled, if I press ESC, although the search window closes.
I need to re-open the search window and remove all characters to see all stations again.

Expected behavior: Search cancels when I press ESC, analogue e.g. to character inventory window.

Tell me if a save is really needed.

**Comment by raiguard** [comment]
This isn't a bug, it's actually intended. However, I do plan on changing this behavior in v0.3.

**Comment by raiguard** [comment]
Search is being re-done in v0.4.0 and will no longer be a thing that is shown or hidden - it is always there. So this issue will be fixed by virtue of the new behavior.

![image](https://user-images.githubusercontent.com/3515394/95670530-c4f76d80-0b49-11eb-8c6a-fd9518fe404f.png)
