### ISSUE TITLE
Support rich text in search results

### ISSUE THREAD

**Issue by xmirakulix** [raiguard/Factorio-LtnManager#89]
#### Is your feature request related to a problem? Please describe.

I would love, if the search window in the station tab would list stations containing the search pattern in rich text form.

Example: 
Search pattern: "low"
Result: list all stations containing a rich text like "[item=low-density-structure]"

Just a nice to have, but would really help.

**Comment by mtomsovic** [comment]
This already works.  I use item links/icons in my train stops as well, and searching for "den" brings up the low density structure stops.

I just loaded up and tried to search for "low" and came up with a bunch of results, not sure what it's searching/looking for but it seems like it's hitting some other meta data for the search aside from station name.

Probably just play around with your search criteria for now. It's worked fine for me normally - copper.. iron.. den.. science, etc.

**Comment by xmirakulix** [comment]
You are right, it's a little weird. Closing...
