### ISSUE TITLE
Status Indicators for Depots have 1 extra blue light status

### ISSUE THREAD

**Issue by Inveli** [raiguard/Factorio-LtnManager#9]
This is is based on the assumption that the "Status" that appears in each depots selection box on the left is supposed to show the status of the lights for each depot (Green for empty, Blue for parked train, etc). If that assumption is incorrect you can ignore this issue.

I noticed that the status indicator seems to count one extra blue light. In my setup I have 3 parking spaces for my 4-8 trains. When all 3 are parked it shows 4 Blue status indicators. If all 3 are out it shows 3 Green and 1 Blue. So it seems to count one extra. I looked around to make sure there wasn't any extra

![Capture](https://user-images.githubusercontent.com/63441826/78968287-bb714800-7ac9-11ea-9509-cfacac73418b.PNG)

**Comment by raiguard** [comment]
Thank you for the report. This has been fixed for the next release:
![image](https://user-images.githubusercontent.com/3515394/79019787-5d2d7f00-7b34-11ea-886c-4ac8df410f34.png)

**Comment by raiguard** [comment]
Erp, wrong issue!

**Comment by raiguard** [comment]
_Now_ it's actually fixed
