### ISSUE TITLE
Crash during standard run of LTN Manager

### ISSUE THREAD

**Issue by xsenk** [raiguard/Factorio-LtnManager#91]
#### Describe the Bug

First I want to thank for amazing mod. Not sure what the actual issue is but:

![ltn manager crash](https://user-images.githubusercontent.com/43633897/85210971-fce16780-b344-11ea-9fc4-08814c4b380a.png)

My guess is that might have to do something with: 
![ltn_status](https://user-images.githubusercontent.com/43633897/85211085-ed165300-b345-11ea-888f-d9d43acd2f43.png)

Had brief look through reference lines of code in your mod / LTN. And if i understood it corectly it crashes on following:
From LTN manager:

```
**552** function ltn_data.on_delivery_completed(e)
  if not global.data then return end
  local train = global.data.trains[e.train_id]
**555**  if not train then error("Could not find train of ID ["..e.train_id.."]") end
```
LTN mod

```
        -- signal completed delivery and remove it
**157**        script.raise_event(on_delivery_completed_event, {train_id = trainID, shipment = delivery.shipment})
        global.Dispatcher.Deliveries[trainID] = nil
```

```
**188** function OnTrainStateChanged(event)
  -- log("(OnTrainStateChanged) Train name: "..tostring(Get_Train_Name(event.train))..", train.id:"..tostring(event.train.id).." stop: "..tostring(event.train.station and event.train.station.backer_name)..", state: "..tostring(event.old_state).." > "..tostring(event.train.state))
  local train = event.train
  if train.state == defines.train_state.wait_station and train.station ~= nil and ltn_stop_entity_names[train.station.name] then
**194**    TrainArrives(train)
  elseif event.old_state == defines.train_state.wait_station and global.StoppedTrains[train.id] then -- update to 0.16
    TrainLeaves(train.id)
  end
end
```

 Im not sure why it it crashed there tho :/. Let me know if I missed some required info / if I can help out somehow in solving it.

For while the mod wasnt working and was whining that standard "Cannot open LTN Manager yet Either translations are not yet finished or LTN hasn't send any data" which got fixed in some of its updates / by running refresh command. Was working fine for couple hours, in last twenty minutes I added 10+ trains, which might have messed up something in processing. 

Im using latest experimental version: 0.18.32 
#### To Reproduce

**I tried three already and in all cases i just load up the save, let game run and in couple mins (on third i swapped game speed to higher, so it was really quick) it crashes on same error.**

#### Save file & Username
[Krastorio 0.18.22 V 2 after GUI update.zip](https://github.com/raiguard/Factorio-LtnManager/files/4808507/Krastorio.0.18.22.V.2.after.GUI.update.zip)

username: forsakenAN

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/4808522/factorio-current.log)

**Comment by xsenk** [comment]
One more thing to add: When I disabled LTN Manager game no longer crashes. So its specifically issue with Manager.

**Comment by alercah** [comment]
I ran into this too after fiddling with some trains into manual mode, and accidentally disconnecting/reconnecting rolling stock. Perhaps that's related?

**Comment by xsenk** [comment]
Atm my base is running 64 trains on auto + one manual artillery train that s idling somewhere. I had LTN Manager disabled for while since it was constantly throwing that. I re-enabled it after you comment after all mods updated plus game on 0.18.36. Left game running for min or two and same thing. I guess i can try to delete all trains and rebuild them. Hoping that might sort it out.... 
![image](https://user-images.githubusercontent.com/43633897/88217179-729b6480-cc5e-11ea-891f-73355fab5845.png)

Maybe worth to mention most of my trains are running with either this module or +20% acceleration
![image](https://user-images.githubusercontent.com/43633897/88217379-c017d180-cc5e-11ea-9cd3-0cb53d644db8.png)

How did you resolved your issue @alercah ? All train rebuild?

**Comment by raiguard** [comment]
Oh jeez, sorry I never noticed this. I am very bad at juggling projects and have been neglecting LTNM.

I will take a look at this issue tonight.

**Comment by xsenk** [comment]
its cool man, since this is more of overview mod on things, that can be simply turned off, i just played without it for while. Appreciating work that you put in. Its really nice to see whats actually happening with trains and i was too lazy do some fancy circuit magic or write own code. Let me know if you needs some more info from me.

**Comment by alercah** [comment]
When I reloaded the save I fiddled with the trains with, it didn't break, so I suspect that was responsible. My definite guess is it was the rolling stock changes that merged/split trains a bunch.

**Comment by xsenk** [comment]
So i tried removing all trains from my game. Than i saved it and started slowly adding them back, always placing couple locos with wagons, setting them for LTN depot and turning them to auto mode. After adding aproximately 20th train it crashed on same error. So not sure what you have done @alercah , but it didn't worked for me :/. Mb its amount of trains and number of spots? Not as crazy as other bases I saw, but its slowly getting there.
![image](https://user-images.githubusercontent.com/43633897/88417946-1d3c9000-cde3-11ea-8a63-7d7b658ac776.png)

**Comment by alercah** [comment]
You should attach the save then so that raiguard can debug it more easily

**Comment by xsenk** [comment]
Sorry you are right, here is latest version of save. It was big for github, so attaching it as drive link. I hope I didn't messed up permission, you should be able to download it. If not let me know and I will try other option. 
https://drive.google.com/file/d/1SSKh9OhS65yBfpPo1jcHPvufX5Q80JTR/view?usp=sharing

**Comment by raiguard** [comment]
This is fixed for the next release.

**Comment by xsenk** [comment]
cool thanks for fixing it. Hope it wasn't complex overhaul ;)
