### ISSUE TITLE
Error loading mods on factorio 0.18.33

### ISSUE THREAD

**Issue by MacsmithVR** [raiguard/Factorio-LtnManager#93]
![Anotación 2020-06-24 145745](https://user-images.githubusercontent.com/53352721/85560706-31963d00-b62b-11ea-8ef9-18e99511be20.png)

**Comment by raiguard** [comment]
Thanks, I'll fix this for the next version.

They changed up some GUI styles in .33 so I need to update my GUIs to match. This affects almost all of my mods.

**Comment by raiguard** [comment]
The patch has been released.

**Comment by MacsmithVR** [comment]
Wow man that was fast, thx for de fix and thx for your mod, awesome work!!

**Comment by raiguard** [comment]
No problem :D
