### ISSUE TITLE
Reoccurence of "Could not find train ID" (#91, #97)

### ISSUE THREAD

**Issue by xsenk** [raiguard/Factorio-LtnManager#98]
![image](https://user-images.githubusercontent.com/43633897/88477880-f34eaf00-cf43-11ea-8049-ce0946fbc9e3.png)

Seems like even after fixed issues #91, #97 same behavior still appears, doesn't seem to be happening as frequently as before. 

Im using latest experimental version: 0.18.36
LTN - 1.13.9
LTN Manager - 0.2.6
username: forsakenAN
Log file: 
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/4977515/factorio-current.log)
Save file: https://drive.google.com/file/d/1SSKh9OhS65yBfpPo1jcHPvufX5Q80JTR/view?usp=sharing

Again i just played for couple mins, without touching any train and game reached error point. So I am guessing putting it on higher game speed and leaving it run should thrown it relatively fast / consistent. 

I am really sorry to bother with it again, but looks like the root cause wasn't completely mitigated.

**Comment by raiguard** [comment]
I ran that save file for over 20 minutes as fast as it would go, and it didn't crash. Are you still able to reproduce it consistently?

**Comment by xsenk** [comment]
Sorry Raiguard and thx again for fixing it. It stopped crashing. Im guessing that re-enabling mod might have fixed it (preobably some remnant in save file or something). But I also lowered down train network usage (added much bigger vagons so they dont run that often, which might had effect also).
